### ISSUE TITLE
DMA_CSELR missing for L4

### ISSUE THREAD

**Issue by Jochen0x90h** [libopencm3/libopencm3#1001]
The data sheet shows DMA1_CSELR and DMA2_CSELR to select which peripheral uses which dma on page 297 and tables 41 and 42. Currently no defines are available for l4 (only for f0 in f0/dma.h). Also no functions to set the register values.

https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/b0/ac/3e/8f/6d/21/47/af/DM00151940/files/DM00151940.pdf/jcr:content/translations/en.DM00151940.pdf

**Comment by karlp** [comment]
I've added the defines at least, but pulling out all the functionality for this channel selection system, for both f0/l4 and anyone else who uses it is bigger than I'm doing personally.  Thanks for the pointer though!
