### ISSUE TITLE
Support for STM32G0x Series

### ISSUE THREAD

**Issue by C47D** [libopencm3/libopencm3#1007]
Hi,

I know this [STM32G0x](https://www.st.com/en/microcontrollers/stm32g0-series.html) microcontrollers are really new, how can we know if is possible for libopencm3 to support them?

Regards

**Comment by karlp** [comment]
I know that @grevaillot is working on a series for them already, or you can start adding things yourself.  Just remember to try and re-use all the existing peripheral code as much as possible, rather than copying it.
