### ISSUE TITLE
wrong link in README.md

### ISSUE THREAD

**Issue by BugerDread** [libopencm3/libopencm3#1033]
Hi,

I think there is wrong link in README.md - section **Installation**, sentence: 
"See the libopencm3-template repository for a template repository..."

the link **libopencm3-template** links to miniblink (https://github.com/libopencm3/libopencm3-miniblink) instead of libopencm3-template (https://github.com/libopencm3/libopencm3-template)

**Comment by karlp** [comment]
thankks for the report!
