### ISSUE TITLE
Why are 16 bit registers defined using MMIO32 for STM32?

### ISSUE THREAD

**Issue by Jochen0x90h** [libopencm3/libopencm3#1082]
Hi!

Some STM32 registers are 16 bit, e.g. the USB control register. But it is defined using MMIO32 in libopencm3/stm32/common/st_usbfs_common.h:

`
#define USB_CNTR_REG		(&MMIO32(USB_DEV_FS_BASE + 0x40))
`

Why isn't MMIO16 used? Then at some places GET_REG() is used to cast to 16 bit which is

`
#define GET_REG(REG)		((uint16_t) *(REG))
`

which looks confusing to me.

**Comment by karlp** [comment]
Probably because of ```Due to the common limitation of APB1
bridges on word addressability, all register addresses are aligned to 32-bit word boundaries
although they are 16-bit wide.``` in the ref manual.  They could probably be changed to MMIO16, and you could drop a cast in one place, but it would only change the legibilty.  If you can change them all and run all the gadget0 tests that would be a perfectly fine PR.
