### ISSUE TITLE
STM32L4 USART_BASE was not declared

### ISSUE THREAD

**Issue by Tarcontar** [libopencm3/libopencm3#1083]
Hi, 

i try to use the UART4 on my STM32L476je, but i get a compile error:

"USART4_BASE was not declared in this scope"

Is UART4 not yet supported? How can I fix this?

greetings 
Tarcontar

**Comment by karlp** [comment]
Try using UART4_BASE directly, not USART4_BASE.  See https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/l4/memorymap.h#L54
