### ISSUE TITLE
Is there any plan to port libopencm3 to TI's C2000 DSP platform?

### ISSUE THREAD

**Issue by rikka0w0** [libopencm3/libopencm3#1084]
I use a lot of STM32 series and TI's F28335 and F28379 in my projects. On STM32 platforms, I can use libopencm3, but for non-ARM platforms, there is no such equivalent lib. I'm thinking about porting this lib to support TI's F28335 or F28379. (Only supports communication peripherals like uart (SCI), spi, i2c and USB, system peripherals like CPU timers, partial support for ADC, DAC and EPWM)
Any idea about this?

**Comment by karlp** [comment]
basically, no, no plans.  At the momemt the infrastructure can use the same compiler for everything, and all the shared header codes for cortex-m families.  You can look at some of the OS+HAL projects like chibios, or nuttx, but I don't really see it ever happening here.  Certainly not while those parts are niche, expensive and not commonly available or used by any project member.  by all means propose a PR if you think you can make this fit in neatly, but I don't believe anyone _currently_ working on the project has any plans or time on leaving the cortex-m world.
