### ISSUE TITLE
Support for STM32L15xx6/8/B-A

### ISSUE THREAD

**Issue by MG-5** [libopencm3/libopencm3#1085]
There is no support for the **generation a** of STM32L15xx6/8/B-A (note the A at the end).

These has some changes like the double amount of RAM.
For migration details see this [technical note](https://www.st.com/content/ccc/resource/technical/document/technical_note/5d/d4/04/90/e6/7b/46/de/DM00114769.pdf/files/DM00114769.pdf/jcr:content/translations/en.DM00114769.pdf)

**Comment by karlp** [comment]
sure, make a PR for the devices.data file.

**Comment by karlp** [comment]
These were all added in 7ff54cb7f075 (note that you must use _a, to avoid issues with the regexps on the -.
