### ISSUE TITLE
【.gitignore】Need to include some files.

### ISSUE THREAD

**Issue by webees** [libopencm3/libopencm3#1096]
These files should not be ignored：

![image](https://user-images.githubusercontent.com/5155291/64054496-d1c13800-cbb9-11e9-8410-41954b12cc1e.png)

https://github.com/libopencm3/libopencm3/blob/master/.gitignore

**Comment by karlp** [comment]
Can you elaborate?  The patterns do match a couple of explicitly committed files, but git doesn't ignore committed files. so... not sure what you're getting at?  Try it, edit one of those files and you'll see that git status still correctly shows you the changes to them.  Feel free to re-open if you think there's something more here.

**Comment by webees** [comment]
When I submit the libopencm3 library code from the local to git, the git repository will get some files missing.

**Comment by karlp** [comment]
please demonstrate further, this is clearly not a problem for anyone else contributing, so I'm completely at a loss to understand your concerns here.
