### ISSUE TITLE
Support for STM32F301C8T6

### ISSUE THREAD

**Issue by Peach8** [libopencm3/libopencm3#1098]
I'm unable to set `DEVICE=stm32f301c8t6` in the Makefile.

Is there a way I can go about adding support for this board simply by appending it to `devices.data`?

Thanks!

**Comment by karlp** [comment]
Good point, thanks for noticing those, not real common I guess.  And yes, just adding it to devices.data works, I've pushed a fix for this for you already now thanks!

**Comment by Peach8** [comment]
Great, thanks!
