### ISSUE TITLE
[new platform] Nordic nRF52 and TI cc26x0

### ISSUE THREAD

**Issue by ildar** [libopencm3/libopencm3#1107]
I heard TI standard framework is ugly.
how hard / are there any plans to add support of Nordic nRF52 and TI cc26x0 ?
Any guides on the topic?

**Comment by karlp** [comment]
I'm not aware of anyone else planning it.  The only guides are the existing targets.  Nordic is rather unlikely, as I imagine it would be ~impossible to get their blobs working without their stack.  Only path forward here is PRs really :)
