### ISSUE TITLE
STM32H7xx support

### ISSUE THREAD

**Issue by westlicht** [libopencm3/libopencm3#1116]
Is there a plan for adding support for STM32H7xx devices? I have used libopencm3 for a previous firmware running on an STM32F4 and would really like to continue using it for a new project running on a STM32H743ZI. From what I understand the H7 line is very close to the F7 line, just with higher clock speeds and more RAM. So my hope is that the effort for a port is not too crazy. I will probably start looking into this unless there is some existing work on that which I could pick up or there is an obvious blocker that I'm not aware of.

**Comment by karlp** [comment]
just needs people doing it and testing it really, same with the rest of the f7 support.  Check for any outstanding PRs for F7 stuff, see if they can be helped along, but yeah, just go for it for h7.
