### ISSUE TITLE
new gcc (g++) and -flto lto1: internal compiler error: Segmentation fault.

### ISSUE THREAD

**Issue by NickaStar** [libopencm3/libopencm3#1122]
if gcc newver then 7.x  (gcc 7 - ok, 8.x and 9.2 - not ok), 
if opencm3 build with "-flto" and some minor changes needed for "lto" (ar -> gcc-ar, etc)
if project language is c++ ( "c" not tested)

while linking/lto g++  lto1: internal compiler error: Segmentation fault.

target: stm32f4.
host: linux, amd64, debian stable or oldstable, or ubuntu16lts
main code (main.cpp) may be as simple as "int main(){ while(1){;}; return 0}", but -lopencm3_stm32f4 is added.

also error reproduced if libopencm3 repacked/simplified and contain only vectors.o, or vectors.o+adc.o objects.

**Comment by karlp** [comment]
If you've made changes to your own fork to turn on LTO, you don't get to report bugs against it :)
