### ISSUE TITLE
i found stupid error

### ISSUE THREAD

**Issue by dltech** [libopencm3/libopencm3#1123]
In file libopencm3/include/libopencm3/stm32/common/rtc_common_l1f024.h
#define RTC_DR_MT_MASK    (1<<12)
may you mean
#define RTC_DR_MT_MASK    1

**Comment by karlp** [comment]
some files use shifted masks, some don't.  I generally prefer all code to use unshifted masks, but without looking further I can't say whether this is "wrong" or not.  What's the actual symptom, is it used wrongly?  You need to provide more information in bug reports

**Comment by dltech** [comment]
Yes, but this file uses shifts and masks separately excepts this string.

**Comment by karlp** [comment]
ok, thanks for the report, fixed
