### ISSUE TITLE
【.gitignore】Please check this code: "include/libopencm3/**/nvic.h"

### ISSUE THREAD

**Issue by webees** [libopencm3/libopencm3#1153]
- First step, please download the file `https://github.com/libopencm3/libopencm3/archive/master.zip`.
- The second step is to extract the files.
- The third step is to enter the directory and execute `git init` and `git add` and `git commit`.
- The fourth step, enter the directory `\include\libopencm3\cm3` to view the status of the file `nvic.h`.
- The `nvic.h` file has been ignored.

![image](https://user-images.githubusercontent.com/5155291/71078646-c58ed400-21c4-11ea-8ba0-84e513aa9356.png)

**Comment by webees** [comment]
https://github.com/libopencm3/libopencm3/issues/1096

**Comment by karlp** [comment]
I'm afraid I still dont understand the problem you're trying to get across.

**Comment by karlp** [comment]
If you're really trying to download a tarball, recreate it as a clean git repository from that point, you can just no include the .gitignore file yourself.  I'm not sure I follow what shoujld be changed in the project though.

**Comment by webees** [comment]
I mean, this file: `https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/cm3/nvic.h` 
shouldn't be ignored, isn't it?

But the description of `.gitignore` is to ignore it. 
`https://github.com/libopencm3/libopencm3/blob/master/.gitignore`

```
# These are generated
include/libopencm3/**/nvic.h
include/libopencm3/**/**/nvic.h
```

Do you need to include the following files, or can these files be generated by recompilation.
```
!include/libopencm3/cm3/nvic.h
!include/libopencm3/dispatch/nvic.h
!include/libopencm3/lm4f/nvic.h
```

**Comment by karlp** [comment]
Ok, I understand this issue now, thank you for clarifying

**Comment by karlp** [comment]
thanks for pushing on this, I've just pushed 911d4be3 to cover this.  the other files you mark (and that git clean -xdn shows if you download the tarball and create a new git repo like you pointed out) are also important to be preserved, so I've included them all, with comments.
