### ISSUE TITLE
It seems the parameter 'max_size' in function 'usbd_ep_setup()' cannot exceed 128 bytes.

### ISSUE THREAD

**Issue by cvabc** [libopencm3/libopencm3#1165]
I follow the call and find in `dwc_ep_write_packet()`, the transfer size assignment is written as `REBASE(OTG_DIEPTSIZ(addr)) = OTG_DIEPSIZ0_PKTCNT | len;`, which did not calculate the actual pktcnt based on `len`. [Link to source](https://github.com/libopencm3/libopencm3/blob/master/lib/usb/usb_dwc_common.c#L211)

**Comment by karlp** [comment]
the stack only supports one packet at at yes, but that's not the same as max size limits?

**Comment by cvabc** [comment]
You mean one packet should lead to `max_size == 64` for full speed device? Hmm, that's weird. Maybe I happened to receive 128 bytes correctly.
