### ISSUE TITLE
No function to go back to 8MHz

### ISSUE THREAD

**Issue by greygraphics** [libopencm3/libopencm3#1171]
Currently, there are many functions allowing to speed up the CPU but none to slow it down again.
Having something like rcc_clock_setup_in_hse_8mhz_out_8mhz() would allow easier power-saving.

**Comment by karlp** [comment]
power saving options are infinite, as are clocking options.  From the function name I presume you're talking about f1, which has all the fixed options. Every other family has a parameterized method, and a few predefined options, and f1 will move there eventually.  We won't be adding any particular slow functions, there's just no end to them all if you start.  I have however (finally) filed https://github.com/libopencm3/libopencm3/issues/1172 to track working on the f1 clock apis.
