### ISSUE TITLE
File libopencm3-master\lib\dispatch\vector_chipset.c missing STM32H7 entry

### ISSUE THREAD

**Issue by bobbatcomcastdotnet** [libopencm3/libopencm3#1217]
The above file does not contain an entry for the STM32H7 chip. This causes the default pre_main() function to be called which results in the FPU not being enabled. Therefore, any use of floating point in an application will cause a segmentation fault. This can be solved by adding the following to this file:

`#elif defined(STM32H7)
#include "../stm32/h7/vector_chipset.c"
`

**Comment by karlp** [comment]
thanks for reporting this!
