### ISSUE TITLE
Error 127 when I attempt to make with cloned repo

### ISSUE THREAD

**Issue by 40339093** [libopencm3/libopencm3#1218]
This is the error message I get.
The file irq.json exists in the directory but irq.json.genhdr doesnt
`GENHDR  include/libopencm3/stm32/f0/irq.json
/usr/bin/env: ‘python’: No such file or directory
make: *** [Makefile:59: include/libopencm3/stm32/f0/irq.json.genhdr] Error 127
`

**Comment by karlp** [comment]
You need python to generate the headers. this is described in https://github.com/libopencm3/libopencm3#prerequisites  (the script will run with either python2 or python3)
