### ISSUE TITLE
adc_set_regular_sequence() is broken

### ISSUE THREAD

**Issue by rma-x** [libopencm3/libopencm3#1230]
The `adc_set_regular_sequence()` functions in adc_common_v1.c and adc_common_v2_multi.c ccontain several expresions that use `&` instead of `&&` and thus they don't work for sequences of more than four (v2) or six (v1) channels.
Additionally I think the whole functions should be refactored to be more efficient.
I plan to provide a patch.

**Comment by karlp** [comment]
cute :)  WHile you're totally correct that it should be &&, because all the tests are bools, the & actually does work anyway, (but, by accident)  If you'd actually tried this you would have seen that the sequences do actually get set correctly.

**Comment by rma-x** [comment]
Yes, it occurred to me afterwards that it might actually work, but only by relying on unguaranteed behavior of comparison operators.
