### ISSUE TITLE
add gc-sections to makefiles

### ISSUE THREAD

**Issue by nerdralph** [libopencm3/libopencm3#1271]
The default makefile flags already include -ffunction-sections and -fdata-sections.  Adding -Wl,--gc-sections saves flash space by omitting the unused sections.  For example it saves 440B on the miniblink example when compiled for the f030.

**Comment by karlp** [comment]
that's something you do when you link your application, not in the library...  The library has to have everything available for it so that people can use it, and they can gc sections in their app.  Do you mean to file this ticket on some other repository?

**Comment by nerdralph** [comment]
This isn't the "root" repository for issues related to multiple of the other repositories?
I thought about opening the issue on the miniblink, examples, and templates repos, but thought it makes more sense to open a single issue.

**Comment by karlp** [comment]
no, make issues in the repositories where the issues are please.
Note that saving space in the miniblink example is completely irrelevant, there's no way you should be copying that repo's makefiles for any real project, and if you do, you're completely on your own :+1: 
The libopencm3-template repo, which _is_ intended to be copied, does include gc-sections like a normal app.  https://github.com/libopencm3/libopencm3-template/blob/master/rules.mk#L87
The libopencm3-examples repo is ~EOL, but if you want to make changes there, you're free to send them as PRs I'm closing this issue on _this_ repository though.
