### ISSUE TITLE
"Your toolchain doesn't support -mcpu=cortex-m7."Using arm-none-eabi-gcc 9.2.1 on WSL2 ubuntu20.04

### ISSUE THREAD

**Issue by Flordsky** [libopencm3/libopencm3#1296]
It reports me error like the picture when I run make .
![{864F4988-E610-4521-8136-0362AC6BBA6C}](https://user-images.githubusercontent.com/42493042/105566006-b0d82480-5d64-11eb-9d78-9c8a86bf9ebc.png)
![{23758CC6-2B60-436E-9B5D-7EB619891D0C}](https://user-images.githubusercontent.com/42493042/105566007-b6356f00-5d64-11eb-8901-0cf5da208a5a.png)

**Comment by ChuckM** [comment]
You have the wrong toolchain installed. Download the toolchain from the arm site and install that. Also, don't build as root, it is unnecessary.

**Comment by karlp** [comment]
Actually, just file this as a bug in the project you're building instead.  This project removed that check in September 2018, in cccc1267c5d
