### ISSUE TITLE
Add SMPS support to STM32H7

### ISSUE THREAD

**Issue by vielster** [libopencm3/libopencm3#1304]
Add PWR driver, and some backward compatible mechanism to utilize this through the RCC (i.e. PLL) interface/configuration.

**Comment by karlp** [comment]
umm, was this meant to be a PR? I don't generally keep issues that are just "library isn't complete" ?

**Comment by karlp** [comment]
I see your comments elsewhere, and the approach looks good, in future, just make the PR, we don't the issue as well normally.
