### ISSUE TITLE
GPIO_USART1_CTS and GPIO_USART1_RTS missing

### ISSUE THREAD

**Issue by rico666** [libopencm3/libopencm3#1326]
Have been looking for these definitions (PA11 and PA12) in

http://libopencm3.org/docs/latest/stm32f1/html/f1_2gpio_8h.html

but to avail. Given the fact they are available for GPIO_USART2... and GPIO_USART3... I consider them missing a bug.

**Comment by karlp** [comment]
sure, you can make a PR for them, it only affects the F1, where someone thought it was worth trying to list everything out.  it's not done for any other family.
