### ISSUE TITLE
Documentation problem in /lib/stm32/common/timer_common_all.c

### ISSUE THREAD

**Issue by supcik** [libopencm3/libopencm3#1353]
Hello,

In the PWM example of the timer:

https://github.com/libopencm3/libopencm3/blob/504dc95d9ba1c2505a30d575371accfe49a69fb9/lib/stm32/common/timer_common_all.c#L54

It seems that the family-specific codes are reversed.

For me, it should be:

```
// For F1....
rcc_periph_clock_enable(RCC_AFIO);
gpio_set_mode(GPIOA, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO8);
// for anyone else
gpio_set_output_options(GPIOA, GPIO_OTYPE_PP, GPIO_OSPEED_50MHZ, GPIO8);
// End of family specific
```

Can someone confirm? And if yes, do you welcome pull-requests?

**Comment by karlp** [comment]
Fixed thanks, this was me mixing up the original code when the alternate form was introduced, thanks for pointing this out
