### ISSUE TITLE
STM32G0 missing comparator support

### ISSUE THREAD

**Issue by neoxic** [libopencm3/libopencm3#1375]
Hello everybody, and first of all, thanks for the great work!
Sorry if I've missed it somewhere (checked through the issues/PRs), is comparator support missing for the G0 family? Thanks!

**Comment by karlp** [comment]
Most families need someone to verify that it's the same peripheral, then add the includes and add the common object, it's normally quite straight forward, but it has to be done manually.  Something like https://github.com/libopencm3/libopencm3/commit/3ab83bc07869dbb3291a721fdb9dc2b1c64a0ddf is normally about all that is required.
