### ISSUE TITLE
STM32H743 -> The SPI interface is completely wrong. 

### ISSUE THREAD

**Issue by dirk1960** [libopencm3/libopencm3#1376]
The SPI interface is completely wrong.
The registers are organized differently and have other names.

If there is such a mistake in it, I'm afraid that I will stumble over many other faults.
This can never have been tested.

**Comment by karlp** [comment]
Correct, it's being worked on in https://github.com/libopencm3/libopencm3/pull/1339
The original h7 submitters were trusted a little too much.
