### ISSUE TITLE
Web page incorrect for dac_load_data_buffer_single

### ISSUE THREAD

**Issue by tomldavis** [libopencm3/libopencm3#1377]
In libopencm3/include/libopencm3/stm32/common/dac_common_all.h:
`void dac_load_data_buffer_single(uint16_t dac_data, data_align dac_data_format, data_channel dac_channel);`
has three input arguments.

The web page, @http://libopencm3.org/docs/latest/stm32f3/html/group__dac__file.html#ga73879c4bf1082c070da2c17ce348e1c7, shows four input arguments for dac_load_data_buffer_single.

Am I missing something?

**Comment by karlp** [comment]
I suspect you have a (quite) outdated localy library? It has four arguments in the current tree: https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/common/dac_common_all.h#L267

we broke the API after the 0.8 tag to support multiple dacs as available on newer parts. (and also make the dac api more like all the other apis)
