### ISSUE TITLE
TIM15, 16 & 17 break functionality not documented correctly.

### ISSUE THREAD

**Issue by tomldavis** [libopencm3/libopencm3#1378]
For all the following library calls:

`timer_enable_break_main_output`, `timer_disable_break_main_output`, `timer_enable_break_automatic_output`, `timer_set_break_polarity_high`, `timer_set_break_polarity_low` and `timer_set_break_lock`, the documentation should be changed to read:

> [in] | **timer_peripheral** | Unsigned int32. Timer register address base TIM1, TIM8, TIM15, TIM16 or TIM17.

Note the these timers are called **General-purpose timers** in the reference manual (RM0365) for the STM32F302. So perhaps the line:

> This setting is only valid for the advanced timers.

should be changed to:

> This setting is only valid for the advanced timers and certain general-purpose timers.

**Comment by karlp** [comment]
given how ST changes functions and adds things, it should probably just be, "This setting is not valid for all timers" :)  I've gone ahead and pushed a doc fixup though, thanks!
