### ISSUE TITLE
STM32: Allow selection of external clock mode 2

### ISSUE THREAD

**Issue by slorquet** [libopencm3/libopencm3#1407]
Hi,

The TIM_SMCR_ECE definition is available but there is nothing to use it in user code.

I suggest addition of a void timer_slave_set_extclockmode2(uint32_t timer_peripheral, uint8_t enabled) API

I can submit a pull request. Should I make the last parameter a bool or an enum?

Thank you for the advice

**Comment by karlp** [comment]
either a bool or a two value enum, like ```void timer_slave_set_polarity(uint32_t timer, enum tim_et_pol pol);```

**Comment by karlp** [comment]
(and yes, just make a PR)

**Comment by slorquet** [comment]
Thanks, just submitted #1408
