### ISSUE TITLE
STM32F303 offset for JSQR should be 0x4C instead of 0x30

### ISSUE THREAD

**Issue by Pickman22** [libopencm3/libopencm3#1412]
I was trying to setup injected conversions for the stm32f303re using the timer module as trigger.
I noticed the JSQR register was not being updated at all. Debugging I noticed the register being updated
was actually SQR which is configuration for regular sequence conversions.

These is the piece of code (adc_common_v2_multi.h):

```C
/* Injected Sequence Register (ADCx_JSQR, x=1..4) JSQR */
#define ADC_JSQR(adc)		MMIO32((adc) + 0x30)
```
Based off the RM0316 reference manual, the correct offset should be 0x4c.
Here's a link to the document: [https://www.st.com/resource/en/reference_manual/rm0316-stm32f303xbcde-stm32f303x68-stm32f328x8-stm32f358xc-stm32f398xe-advanced-armbased-mcus-stmicroelectronics.pdf](url)

Not sure if any other macro in the ADC driver is wrong.

**Comment by karlp** [comment]
thanks very much!
