### ISSUE TITLE
Object crc_v2.o missing in the Makefile for G0

### ISSUE THREAD

**Issue by kernkraftzwerg** [libopencm3/libopencm3#1428]
In /lib/stm32/g0/Makefile there is no object crc_v2.o
I'm currently using the STM32G030C8T6, which provides this CRC_V2 API.

**Comment by karlp** [comment]
correct, no-one's tested it and submitted the updates.    I'm closing this issue though, we don't keep issues tracking missing functionality, as it's too open ended.
