### ISSUE TITLE
In crc_v2.c there are no functions for 8-bit and 16-bit access to CRC_DR

### ISSUE THREAD

**Issue by kernkraftzwerg** [libopencm3/libopencm3#1429]
According to specification and my tests the STM32G0 register CRC_DR also provides 8-bit and 16-bit write access for calculating the CRC bytewise and wordwise, which is different to STM32F1 that only has 32-bit write access.

**Comment by kernkraftzwerg** [comment]
To clarify the issue: there are macros for 8-bit and 16-bit access (CRC_DR8 and CRC_DR16), but no functions crc_calculate8() and crc_calculate16().

**Comment by karlp** [comment]
ok, sure, you can make a PR for extra functionality, but we're not keeping issues around for desired functionality, sorry.
