### ISSUE TITLE
g0 function adc_set_regular_sequence() unintentionally clears all ADC interrupt flags

### ISSUE THREAD

**Issue by kernkraftzwerg** [libopencm3/libopencm3#1443]
In adc.c function adc_set_regular_sequence() there are multiple lines for clearing the CCRDY flag from ADC_ISR:
ADC_ISR &= ~ADC_ISR_CCRDY;

According to the specification the flags are cleared by writing a 1 to the register, so the above instruction clears all pending flags but not CCRDY. It should be:
ADC_ISR = ADC_ISR_CCRDY;

Don't use |= because this would clear all flags.

**Comment by karlp** [comment]
thanks for this! nice catch.  I checked all the other adc-v2 implemenations as well, and fortunately only g0 was suffering from this.
