### ISSUE TITLE
Windows 10 : Makefile doesn't work

### ISSUE THREAD

**Issue by hyxdxhb123** [libopencm3/libopencm3#1444]
When I download libopcm3 by using git bush, then I try to make in the git bash, it suddenly went wrong

![image](https://user-images.githubusercontent.com/62733257/200318153-bcf4d14f-c6b0-4496-81df-d4c7445553cc.png)

so how to fix it?

I did't use linux , I use Windows 10 20H2

**Comment by karlp** [comment]
you need python, and probably to adjust your path. https://github.com/libopencm3/libopencm3#prerequisites

**Comment by zitianHuang** [comment]
me too. But I already have python and set the path, can you tell me how you solved it?
