### ISSUE TITLE
STM32F3 RTC incorrec define in header

### ISSUE THREAD

**Issue by nroff-man** [libopencm3/libopencm3#1446]
hi

f3/rtc.h defines LIBOPENCM3_RTC_F3_H when it should define LIBOPENCM3_RTC_H

**Comment by karlp** [comment]
Could you please clarify this? why what, what's wrong with it?

**Comment by nroff-man** [comment]
RTC support does not build on F3 platform and if this is
your intended behaviour then ignore this report.

**Comment by nroff-man** [comment]
RTC is not supported on the F3 platform (it is missing support
in the libarary), further to this, the registers and also not available
due to the define mentioned.
this could be intentional or an oversight.

**Comment by karlp** [comment]
Thanks for clarifying what you meant.  The more context you can give for issues the easier it is for someone to address.
