### ISSUE TITLE
g0 function adc_set_sample_time_on_all_channels() uses wrong shift value for clearing the channel selection bits

### ISSUE THREAD

**Issue by kernkraftzwerg** [libopencm3/libopencm3#1448]
The bits 8 to 26 in ADC_SMPR are used to select the sampling rate for each ADC channel. The function tries to clear all those bits for selecting SMP1 for all channels, but uses the wrong shift value:

reg32 &= ~((ADC_SMPR_SMPSEL_MASK << ADC_SMPR_SMP1_SHIFT) | (ADC_SMPR_SMP1_MASK << ADC_SMPR_SMP1_SHIFT));

should be:

reg32 &= ~((ADC_SMPR_SMPSEL_MASK << ADC_SMPR_SMPSEL_SHIFT) | (ADC_SMPR_SMP1_MASK << ADC_SMPR_SMP1_SHIFT));

**Comment by karlp** [comment]
thanks for reporting this!

**Comment by kernkraftzwerg** [comment]
Wow, that was fast! You are welcome :)
