### ISSUE TITLE
How to use timer14 with STM32F746 device

### ISSUE THREAD

**Issue by markusljh** [libopencm3/libopencm3#1450]
I try to use timer14 by following the timer2 example.
but the compiler show below message.

project.cpp:63:21: error: 'NVIC_TIM14_IRQ' was not declared in this scope; did you mean 'NVIC_TIM4_IRQ'?
   63 |     nvic_enable_irq(NVIC_TIM14_IRQ);

How to use timer9~timer14 by using libopencm3 correctly. 
Could you provide sample [code?](url)
Thanks.

Below is my code:
static void timer_setup(void)
{
    timer_set_mode(TIM14,
                 TIM_CR1_CKD_CK_INT,
                 TIM_CR1_CMS_EDGE,
                 TIM_CR1_DIR_UP);
    timer_disable_preload(TIM14);
    timer_continuous_mode(TIM14);

    timer_set_prescaler(TIM2, TIMER_PRESCALER); /* Setup TIMx_PSC register. */
    timer_set_period(TIM2, TIMER_PERIOD);       /* Setup TIMx_ARR register. */
  
    /* Setup interrupt. */
    timer_enable_irq(TIM14, TIM_DIER_UIE);
    nvic_enable_irq(NVIC_TIM14_IRQ);
  
    timer_enable_counter(TIM14);
}

Best Regards

**Comment by karlp** [comment]
The vector is shared, use the name tim8_trg_com_tim14.
See 
![image](https://user-images.githubusercontent.com/127907/210419818-fcde8c5d-c27f-4f5a-9faf-382b56544554.png)
(when in doubt, use the names from the reference manual)
