### ISSUE TITLE
Support for RP2040 ARM Cortex-M0+ MCU

### ISSUE THREAD

**Issue by hattesen** [libopencm3/libopencm3#1496]
Hi,

Is there any plans to add support for the (popular and low cost) [RP2040](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) ARM Cortex-M0+ MCU?

I have quite a few projects that I have ported accross STM32F0, STM32G0 and RP2040 MCU architectures, when the availability and/or pricing of specific MCU models suddenly forces such a change, so it would be ideal to have support for the RP2040 in libopencm3.

Does a "Porting Guide" exist, that explains the process/steps involved in porting libopencm3 to a new ARM Cortex architecture, and minimum implementation support to become an "official" option in libopencm3, so I could possibly attempt to get started myself?

**Comment by karlp** [comment]
because when libopencm3 started, the cmsis headers weren't permissively licensed, like they are now.

**Comment by karlp** [comment]
As for the issue itself, there's no porting guide, and people who want RP2040 are welcome to try and submit support for it.  I am not personally working on it.  We also don't really keep "wishlist" tickets open, they just get in the way of real issues, so I'm closing this for now.
