### ISSUE TITLE
Filename collision, no lib prefix

### ISSUE THREAD

**Issue by mrx23dot** [libopencm3/libopencm3#1517]
I find it weird that HAL uses common short file names like **adc.c and wdt.c** 

HALs usually have a prefix (like **stm32f1xx_hal_adc.c**)
So we could implement our middleware/wrapper in adc.c / wdt.c
I wouldn't name my custom files as myapp_adc.c  (because it's inefficient, and they change more often then library files)

If you say that filename collision is not a concern because relative include path is used, then I would say it's still annoying if you search for "adc" in VScode and two files show up with same name.
Some compilers might even require unique file names, since **object files are flat in build dir**
Not to metion static analysers might omit file paths too.

Fun fact, in some gcc variant adc.h is an includable library header.

It would be so much nicer/professional to use prefixes for the lib files, e.g. `cm_adc.c` `cm_adc.h`

**Comment by karlp** [comment]
using consistent naming as referred to in #570 is still a goal when people are making api changes, and to be thought about whenever new apis are brought in.

changing the names of the library source because vscode is a terrible editor isn't happening though.

**Comment by mindnever** [comment]
One could argue that environment with flat obj structure is fundamentally broken anyway and why would it be library's fault if file names clash?
