### ISSUE TITLE
Thanks and support to maintainers

### ISSUE THREAD

**Issue by f4grx** [libopencm3/libopencm3#1537]
Hello,

In light of the recent xz incident I want to use this opportunity to send my deepest thanks and consideration to maintainers of this project, whatever the public progress may be.

I also want to apologize about any previous messages where I may have been pushing for modifications of leadership or management. It was definitely a bad behaviour and I will refrain myself from such behaviour again.

**Comment by karlp** [comment]
Don't worry about it :)  The complaints were and are still _valid_
