### ISSUE TITLE
Support for STM32H7 series

### ISSUE THREAD

**Issue by OrnellaBenzi** [libopencm3/libopencm3#1544]
We are currently starting to migrate from a STM32F4 micro to a STM32H7 to improve performance of our products, we are using the PlatformIO IDE and wanted to keep using the libopencm3 framework.
The question is, is the STM32H7 supported in the framework and reliable??

**Comment by karlp** [comment]
it's probably not as complete as you might like, but you'd have to evaluate it yourself.  You can look at the h7 makefiles to see what modules are currently turned on.  It's _certainly_ less tested and developed than the f4 support.
