### ISSUE TITLE
H7 Wrong RCC Register Defines

### ISSUE THREAD

**Issue by OrnellaBenzi** [libopencm3/libopencm3#1547]
I found an error in the definition of the RCC registers:
`/* PLLs are 1-based, so reference macros to 1..3, using index 0 will give undefined behavior. */`

`#define RCC_PLLDIVR(n) MMIO32(RCC_BASE + 0x030 + (0x08 * ((n) - 1)))`
`#define RCC_PLLFRACR(n) MMIO32(RCC_BASE + 0x030 + (0x08 * ((n) - 1)))`

![image](https://github.com/libopencm3/libopencm3/assets/92052026/5795c19c-39d4-4148-b430-3fe74ef266a4)

Both RCC_PLLDIVR and RCC_PLLFRACR have the same definition, but RCC_PLLFRACR should be 
 `#define RCC_PLLFRACR(n) MMIO32(RCC_BASE + 0x034 + (0x08 * ((n) - 1)))` (+0x004)

**Comment by karlp** [comment]
thanks for reporting this!
