### ISSUE TITLE
What's the proper way to integrate this library with CMake?

### ISSUE THREAD

**Issue by VictorQueiroz** [libopencm3/libopencm3#1551]
I found two relevant examples showing how to integrate `libopencm3` with CMake, but they could have been more straightforward. Is there a standard recommendation for integrating 'libopencm3' with a CMake build system?

**Comment by karlp** [comment]
there's nothing standard built in by libopencm3 itself.  It's "like any other" external make project, from the point of view of cmake.  It becomes a matter of taste for cmake people how they like to do that next.
