### ISSUE TITLE
Incorrect offset for STM32 G4 dual bank option bit

### ISSUE THREAD

**Issue by amcnicoll** [libopencm3/libopencm3#1559]
https://github.com/libopencm3/libopencm3/blob/b8e6e5d373ea7670ce52e46ff945a4c2c9b82d7c/include/libopencm3/stm32/g4/flash.h#L146

Should be 22.

![image](https://github.com/user-attachments/assets/a6cbfa1d-6325-4fad-9a16-6fe21984c7c5)

Option bytes got a lot of traffic in the revision table, so it's possible this was an error present in Revision 4 of the reference manual, which was referenced at the time.

**Comment by karlp** [comment]
nah, just an error. rev3 of the datasheet that I had locally has it in 22 already. fixed thanks!
