### ISSUE TITLE
Add support for building out of the source directory

### ISSUE THREAD

**Issue by noupu** [libopencm3/libopencm3#221]
It’s sometimes handy to be able to build the software out of its source directory (for example, when experimenting with build options), and libopencm3 is no exception.

Example:

```
$ mkdir build1
$ cd build1
$ make srcdir="$PWD"/.. -f ../Makefile ${some_more_options}
$ mkdir ../build2
$ cd ../build2
$ make srcdir="$PWD"/.. -f ../Makefile ${different_options}
```

Apart from the makefiles, `scripts/irq2nvic_h` is likely to be changed.

I hope to craft a patch shortly.

**Comment by karlp** [comment]
If anyone still wants/needs this, they'll need to provide a patch for it sorry.
