### ISSUE TITLE
SPI and STM32F4 not working

### ISSUE THREAD

**Issue by ChuckM** [libopencm3/libopencm3#232]
So there are at least a few issues with SPI and STM32F4 and the current. Library. The minimal test code which is something like this:

`... gpio pin setup  ...
    spi_init_master(SPI2, 4000000, SPI_CR1_CPOL_CLK_TO_1_WHEN_IDLE,
                    SPI_CR1_CPHA_CLK_TRANSITION_1, SPI_CR1_DFF_8BIT,
                    SPI_CR1_LSBFIRST);
    spi_enable(SPI2);`

Will leave the SPI port disabled and 'MODF' set in the status register. The MODF bit is a 'Mode Fault' which occurs because the F4 tries to get fancy with the NSS/chip select and decides that even if it isn't enabled or connected that someone tried to select us and boom, you get mode fault. You can "fix" that aspect of it by adding:

`SPI_CR2(SPI2) |= SPI_CR2_SSOE;`

After the init call to force the unit to stay in master mode and ignore possible transitions on the NSS pin. This is explained poorly on 876 of the REV5 data sheet under Master Mode Fault, and why you have to set it this way in step 5 of "Configuring the SPI in master mode" in the manual on page 861 which says:

**5. If the NSS pin is required in input mode, in hardware mode, connect the NSS pin to a high-level signal during the complete byte transmit sequence. In NSS software mode, set the SSM and SSI bits in the SPI_CR1 register. If the NSS pin is required in output mode, the SSOE bit only should be set. This step is not required when the TI mode is selected.**

So if you aren't using NSS, and your a master, and you're doing bi-directional transfers, you seem to have to set the SSOE bit.  I'm still trying to nail down exactly how they expect this to work for real, but its gotten my SPI code talking which was not the case up to this point.

**Comment by WRansohoff** [comment]
Sorry to necropost, but I ran into this same issue with the STM32F0 line; setting up SPI in master mode with software NSS resulted in the 'Mode Fault' bit being set in SPIx_SR and the peripheral not being set up.

But setting the 'SSOE' bit in SPIx_CR2 got things working for me, too - thanks! It seems bizarre though, since from that bit's description, it sounds like setting it enables the NSS signal which I'm trying to ignore. ("SS output is enabled in master mode and when the SPI interface is enabled. The SPI interface cannot work in a multimaster environment.")

Maybe it's just worded confusingly; I don't have a very good understanding of the protocol. But anyways, +1 for Chuck's solution, it's not just for the F4 series.

**Comment by deadsy** [comment]
Thanks for the info - I was having the same problem on the stm32f407 - ie MODF as soon as the SPE is set causing it to turn off master and turn off SPE. With SSOE turned on the issue stops and the peripheral stays enabled.

Looks better now.

`
mb997c*> regs SPI2 *
CR1             : 40003800[31:0] = 0x0000026f   control register 1                                
  BIDIMODE[15]  : 0                             Bidirectional data mode enable                    
  BIDIOE[14]    : 0                             Output enable in bidirectional mode               
  CRCEN[13]     : 0                             Hardware CRC calculation enable                   
  CRCNEXT[12]   : 0                             CRC transfer next                                 
  DFF[11]       : 0                             Data frame format                                 
  RXONLY[10]    : 0                             Receive only                                      
  SSM[9]        : 1                             Software slave management                         
  SSI[8]        : 0                             Internal slave select                             
  LSBFIRST[7]   : 0                             Frame format                                      
  SPE[6]        : 1                             SPI enable                                        
  BR[5:3]       : 5                             Baud rate control                                 
  MSTR[2]       : 1                             Master selection                                  
  CPOL[1]       : 1                             Clock polarity                                    
  CPHA[0]       : 1                             Clock phase                                       
CR2             : 40003804[31:0] = 0x00000004   control register 2                                
  TXEIE[7]      : 0                             Tx buffer empty interrupt enable                  
  RXNEIE[6]     : 0                             RX buffer not empty interrupt enable              
  ERRIE[5]      : 0                             Error interrupt enable                            
  FRF[4]        : 0                             Frame format                                      
  SSOE[2]       : 1                             SS output enable                                  
  TXDMAEN[1]    : 0                             Tx buffer DMA enable                              
  RXDMAEN[0]    : 0                             Rx buffer DMA enable                              
SR              : 40003808[31:0] = 0x00000002   status register                                   
  TIFRFE[8]     : 0                             TI frame format error                             
  BSY[7]        : 0                             Busy flag                                         
  OVR[6]        : 0                             Overrun flag                                      
  MODF[5]       : 0                             Mode fault                                        
  CRCERR[4]     : 0                             CRC error flag                                    
  UDR[3]        : 0                             Underrun flag                                     
  CHSIDE[2]     : 0                             Channel side                                      
  TXE[1]        : 1                             Transmit buffer empty                             
  RXNE[0]       : 0                             Receive buffer not empty                    

`

**Comment by karlp** [comment]
@deadsy what tool are you using for those reg dumps?

**Comment by deadsy** [comment]
@karlp 

My own tool: https://github.com/deadsy/pycs

It's an SWD based debugger that takes the vendor provided SVD files and extracts the register descriptions thereby making it easy to look under the hood of these various cortex m chips.
