### ISSUE TITLE
Populate current processor clock speed

### ISSUE THREAD

**Issue by BuFran** [libopencm3/libopencm3#236]
Current versions of RCC module populates variables  rcc_ppre1_frequency and  rcc_ppre1_frequency, that has not descriptive name.

The idea of this issue is to create a global set of variables, common for all stm32 family, correctly filled with current clock speeds of appropriate busses.

rcc_frequency_core
rcc_frequency_apb1
rcc_frequency_apb2
rcc_frequency_ahb

The core clock speed information is missing in the current lib.

**Comment by mox-mox** [comment]
I just ran across the same issue and created a quick patch to populate at least the AHB clock speed (which should be equal to the core speed, correct?). It just adds one data member to the clock_scale_t struct which defines the AHB speed and sets rcc_ahb_frequency in void rcc_clock_setup_hse_3v3(const clock_scale_t *clock).

See https://gist.github.com/mox-mox/e21ee91e9ee9417badb5

Could you please merge this into libopencm3?

**Comment by karlp** [comment]
@mox-mox please, if you have changes you want commited, make a regular pull request for them.

**Comment by mox-mox** [comment]
Done :)
https://github.com/libopencm3/libopencm3/pull/467

**Comment by karlp** [comment]
I've been back looking at things like this, and I'm now convinced of the validity of keeping the existing globals and adding one for core clock.

**Comment by mox-mox** [comment]
Honestly, I don't care anymore.

**Comment by karlp** [comment]
no, that's fine, I'm just pulling in parts of it now, and leaving comments for anyone else following the ticket

**Comment by karlp** [comment]
Via 5738e9515d1a83dab72aada1865c3a2982754bea and the partial commits before it, all of the ahb frequencies are in, doesn't seem to be any particular need for a separate core clock.
