### ISSUE TITLE
[USB] set configuration bogus value check

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#293]
Their no checking on the "new configuration number" (in req->wValue) in usb_standard_set_configuration <usb_standard.c>.
if host send some bogus value, it will just just accept the value and send the callback the bogus value (if their is one). 
Also, the callback function is not allowed to report the bogus value (according to API).

**Comment by karlp** [comment]
This is fixed in 7cd72125779641b97532b49fa89fbfc410bc85df
