### ISSUE TITLE
Should include stdint.h and stdbool.h

### ISSUE THREAD

**Issue by agalakhov** [libopencm3/libopencm3#301]
Hi,

I found that cortex.h uses bool and uint32_t types that are not declared by default:
libopencm3/cm3/cortex.h:84:1: error: unknown type name 'bool'

These types are declared in stdint.h and stdbool.h in C99. Please include these files where needed.

Regards,
Alex

**Comment by karlp** [comment]
Closed in  aac78ba464f3bd66d9eb07433baba7ce70723461  but only the basic portion, of fixing the cm3/cortex.h header.  Any other files found not including their prerequisites, please file new bugs
