### ISSUE TITLE
Multiple configuration will NULL the control endpoint ( + many other related minors)

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#302]
usb/usb_standard.c  usb_standard_set_configuration()
~~1) in this function , when their are multiple configuration, the loop inside the if will clear all callback (including ep0 callback) leading *doom* (device unresponsive).~~

2) their is no checking for invalid/bogus values wValue(bConfigurationNumber). as per doc usb2.0 p257 if any config. is invalid, request error should be issued. also, if bConfiguration=0 then device should be place in address state.
(their's more info on the page)

3)if (req->wValue == usbd_dev->current_config) comparision is not required since their is nothing mentioned related given configuration is already set.

**Comment by karlp** [comment]
All the "set config" type issues from the original ticket are resolved by tests in current master.  To keep a clean ticket for any further issues, I'd like to start a new issue if needed.
