### ISSUE TITLE
Macros like GPIO_IDR use too little parenthesis. 

### ISSUE THREAD

**Issue by rewolff** [libopencm3/libopencm3#321]
The definition is now: 

#define GPIO_IDR(port)                     MMIO32(port + 0x10)

which evaluates to something unwanted if you call: 
  GPIO_IDR (pin_id & PORTMASK)

because: 
  MMIO32(pin_id & PORTMASK + 0x10)
is something else than what it should be: 
  MMIO32((pin_id & PORTMASK) + 0x10)

This probably holds for ALL MMIO32 defines..... Auch!

**Comment by karlp** [comment]
fixed via c72f3d5 thanks for the report!
