### ISSUE TITLE
Controller Area Network (CAN) STM32 module is not documented

### ISSUE THREAD

**Issue by ihanick** [libopencm3/libopencm3#358]
CANbus module is available for stm32, 
The module is common for stm32, functions and parameters are described properly with doxygen markup, but doxygen is not generating documentation for lib/stm32/can.c source file

There are several sample for stm32f1 in libopencm3-examples.
The API is tested and working with stm32f4.

It's important to mention that canport parameter for can_filter_init, can_filter_id_mask_16bit_init, can_filter_id_mask_32bit_init, can_filter_id_list_16bit_init, can_filter_id_list_32bit_init functions could be only CAN1, because CAN2 is not "full" CAN IP block and filter is shared between CAN1 and CAN2.

**Comment by BuFran** [comment]
I was finished this move in my repo, but I found that the API was not so stable to use in all platforms (there was slight changes between platforms, or between definitions and RM, so for me, it works on F4, untested at others.)

Minimally I can put here the file movement commit soon.

**Comment by karlp** [comment]
It can still get some grouping to tidy it up, but it's included now after redoing the doxygen source list generation
