### ISSUE TITLE
stm32f107 connectivity line primary remap issue

### ISSUE THREAD

**Issue by brabo** [libopencm3/libopencm3#369]
because the stm32f107 connectivity line uses in AFIO_MAPR some remap bits that are reserved in other lines (SPI3 remap for example).
this line 171 of lib/stm32/f1/gpio.c prevents these from being set:

AFIO_MAPR |= (swjdisable & AFIO_MAPR_SWJ_MASK) | (maps & 0x1FFFFF);

as a workaround i have changed this line to:

AFIO_MAPR |= (swjdisable & AFIO_MAPR_SWJ_MASK) | maps;

which is probably just fine for the f1 connectivity line, but may not be suitable for other lines.

**Comment by karlp** [comment]
Fixed via the merge of https://github.com/libopencm3/libopencm3/commit/eebef017186cfbd2a4663c3dda1eb98dad6f1725 but #503  will extend this further.
