### ISSUE TITLE
f0 uses old usart code and thus can't do 9 bit characters

### ISSUE THREAD

**Issue by ChuckM** [libopencm3/libopencm3#371]
Mark notes that the F0 doesn't correctly send 9 bit characters when the USART is in 9 bit mode. This is because the implementation of usart_send (and usart_recv) is written to only send and receive 8 bit bytes. Both need to be fixed to support 16 bit uint16's as the data and should probably switch to using usart_common_all.h for their prototype declarations.

**Comment by karlp** [comment]
This was fixed initially in 7ee1d948e99b89d722ab396b2fee3ab5cd3b7437 via https://github.com/libopencm3/libopencm3/pull/651 because this issue had unfortunately been forgotten.  It's remained fixed after the move to the common usart-v2 code.
