### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ksarkies** [libopencm3/libopencm3#4]
The project currently has embryonic doxygen markup. I'm willing to put in some mileage to establish a framework and to fill in some of the documentation. Even though the API isn't stable, I consider this to be quite important to make the library more accessible to users and it's easy enough to modify along with any API changes.

I'm putting this as an issue to seek comments or suggestions, if there are any. The proposal is initially to set up the doxygen structure in a global header file and to provide an example for one or two functions. The rest will be filled in later as it is completed.

**Comment by karlp** [comment]
the doxygen ksarkies setup was awesome as hell and we wouldn't be where we are without it.  I think our documentation has come along way though, and i'm not sure we need to keep this ticket for it anymore inparticular. thanks for all the groundwork!
