### ISSUE TITLE
for ARM (on STM32) usb descriptor and usbd_control_buffer alignment

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#401]
struct usb_device_descriptor and uint8_t usbd_control_buffer should atleast be 16bit aligned.
these are used to by 16 oriented copy operation for STM32 usb PMA.
if not, on ARM hard-fault occur due to aligned memory access constraint.
(Please Document this somewhere to save someone from headache).

**Comment by fenugrec** [comment]
+1000 !, just got hit by this. I think this can be generalized to all ST "usbfs_v2" peripherals (F0 and L0) since both M0 and M0+ cores do not support unaligned memoery access ?

**Comment by karlp** [comment]
Fixed via merge of https://github.com/libopencm3/libopencm3/pull/653
