### ISSUE TITLE
bit definitions

### ISSUE THREAD

**Issue by dltech** [libopencm3/libopencm3#413]
Why do you repeat register names in the bit definitions? For example, counter enable bit defined like TIM_CR1_CEN instead of CEN. I think that this naming method is excess, increases code length and makes it more difficult to find the appropriate bit definition. Thus, if you want to set CEN bit in TIMx_CR1 register, you are also know that this bit corresponds to TIMx_CR1 register.

**Comment by karlp** [comment]
It's meant to make it easier to find them, when there's lots of lots of definitions, and to help know what bits are available in which register, by keeping the namespaces predictable.  There are EN type bits in many registers, not always in the same posititions for instance.  It also helps you avoid setting a CR1 bit definition in a CR2 register, that sort of thing.
