### ISSUE TITLE
Using Linaro-gcc 2014-09 version to compile the libraries

### ISSUE THREAD

**Issue by CasperChua** [libopencm3/libopencm3#419]
I am using Linaro gcc 2014-09 version. I wonder if there a quick guide to compile the examples in libopencm3.

**Comment by ChuckM** [comment]
@CasperChua I am pretty sure the version of gcc that comes with Linaro is for Linux based systems, you want an embedded version of gcc, you can build one from the [gcc-arm-embedded][gcc] source tarball.

[gcc]: http://launchpad.net/gcc-arm-embedded

**Comment by BuFran** [comment]
Hi Casper, I agree with ChuckM in a way that Linaro is not designed for bare metal work. 

The compilation for bare metal is possible only with gcc-arm-embedded and with LLVM (work in progress)

Closing this issue as invalid
