### ISSUE TITLE
lpc17xx uses -O0 by default

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3#429]
No idea why, is there any particular issue with lpc17xx that means it uses -O0 instead of -Os by default like all other makefiles?

**Comment by sgissi** [comment]
Not at all. I'm moving, my boards are in a box, I can test in two weeks or so but with so little code on lpc17xx I cannot see why it wouldn't, if so, is a bug to be fixed...

**Comment by karlp** [comment]
fixed in a21da3a
