### ISSUE TITLE
Interrupt driven USB for STM32?

### ISSUE THREAD

**Issue by dword1511** [libopencm3/libopencm3#435]
I saw that libopencm3 has support for interrupt driven USB on LM4F (`usb_enable_interrupts` and `usb_disable_interrupts`).

By enabling and handling the interrupts and removing the polling in the loop, USB seems to be working well:

```
void main(void) {
  ......
  nvic_enable_irq(NVIC_USB_LP_CAN_RX0_IRQ);
  nvic_enable_irq(NVIC_USB_WAKEUP_IRQ);
  ......
}

void usb_wakeup_isr(void) {
  usbd_poll(usbd_dev);
}

void usb_lp_can_rx0_isr(void) {
  usbd_poll(usbd_dev);
}
```

**Comment by rkreis** [comment]
Another example without interrupts, but `wfi` (which allows using sleep modes) combined with `usb_poll`: https://github.com/rkreis/usb_testcase
Relevant: #360 and https://github.com/kuldeepdhaka/libopencm3/commit/5f873fc45b5c8c6b8e6fd33557f99d41aa9a9108

**Comment by karlp** [comment]
a few people have written it like that, there was some discussion that this was only suitable really in certain test cases, but sure, you can call poll however you like, that's entirely up to you.

**Comment by schodet** [comment]
If you do this with OTG IP, see #531.
