### ISSUE TITLE
adc function naming inconsistancy

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#456]
https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/f0/adc.h#L324
adc_power_off and adc_power_on

https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/common/adc_common_v1.h#L359
adc_power_on and adc_off

https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/f1/adc.h#L413
why depriciate information here?

https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/f3/adc.h#L872
adc_power_on, adc_off

why not stick to {adc_on, adc_off} or {adc_power_on, adc_power_off}. afaik, all they do is power up/down adc.

**Comment by karlp** [comment]
this has now been fixed by landing the big f0/f3/l4 adc cleanup tree
