### ISSUE TITLE
USB Buffer alignment 

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#461]
on stm32 usb, 16bit alignment is required 
https://github.com/libopencm3/libopencm3/blob/master/lib/usb/usb_f103.c#L230
what if buf is 8bit aligned, it would cause incorrect behaviour in copying.

found by @rkreis

**Comment by kuldeepdhaka** [comment]
a special case of this issue: #401

**Comment by fenugrec** [comment]
Status: this is fixed for st_usbfs_v2 peripheral, and if I understand correctly it's not an issue for st_usbfs_v1 , because the v1 peripheral is not found on M0/M0+ cores ?

( https://github.com/libopencm3/libopencm3/blob/master/lib/stm32/st_usbfs_v1.c#L57 )

**Comment by karlp** [comment]
as noted, this is fixed, and has been for a while
