### ISSUE TITLE
stm32/usb_desc.h?

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#462]
https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/stm32/usb_desc.h
what is usb_desc.h doing in stm32/

**Comment by rikvdh** [comment]
I agree. The file can be removed if all references change to https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/usb/usbstd.h because most structures in are identical.

**Comment by karlp** [comment]
closed via rebase.  no direct users in lib or in examples.
