### ISSUE TITLE
I2S2_ext and I2S3_ext are swapped in the memory map for STM32F4 devices

### ISSUE THREAD

**Issue by mox-mox** [libopencm3/libopencm3#465]
In the file libopencm3/include/libopencm3/stm32/f4/memorymap.h, lines 51 and 54, the memory locations for the I2Sx_extended base addresses are swapped.

The correct values would be
#define I2S3_EXT_BASE			(PERIPH_BASE_APB1 + 0x4000)
#define I2S2_EXT_BASE			(PERIPH_BASE_APB1 + 0x3400)

**Comment by karlp** [comment]
thanks for reporting this!
