### ISSUE TITLE
libopencm3/stm32/l1/nvic.h is missing

### ISSUE THREAD

**Issue by joostrijneveld** [libopencm3/libopencm3#466]
In `/include/libopencm3/dispatch/nvic.h`, the file `libopencm3/stm32/l1/nvic.h` is being included. However, this file does not seem to exist (or at least not in this repository). See [this file](https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/dispatch/nvic.h#L18) for the offending line.

**Comment by karlp** [comment]
Run make first.  It's not just the L1, it's all of them.  This is a built library, not a set of files you include.
