### ISSUE TITLE
USB: st_usbfs : bad ep_rx_bufsize calculation

### ISSUE THREAD

**Issue by fenugrec** [libopencm3/libopencm3#476]
in lib/usb/usb_f103.c ::usb_set_ep_rx_bufsize() ( https://github.com/libopencm3/libopencm3/blob/master/lib/usb/usb_f103.c#L88 ), the code will produce invalid values for the NUM_BLOCK field of the USB_COUNTn_RX register (refer to RM0008 table 177 / RM0091 table 127) :
- sizes <= 62 are rounded up (ok) but not shifted >>1
- sizes > 62 are rounded down (inconsistent) and not re-adjusted
- (minor) : size==0 is not checked; but is not allowed for NUM_BLOCK

The effect of this is that the actual size set (and used by the peripheral) is larger than the requested size.

This is conjecture, but a bug (admittedly very improbable) would occur if :
- the user sets a first EP RX buffer size, and assumes the next buffer (could be any EP buffer) starts at &RX_BUFFER + <asked_size>,
- data is written at the real &TX_BUFFER (not where the user expected)
- the host sends a packet that is longer than <asked_size>, but respects the actual size set in the USB_COUNTn_RX register. This over-writes the next buffer in packet memory.

**Comment by fenugrec** [comment]
I'm having trouble making a PR but the correct function would be:

```
/*
* Valid for at least F102, F103, and F0 devices
*/
static void usb_set_ep_rx_bufsize(usbd_device *dev, uint8_t ep, uint32_t size)
{
	(void)dev;
	if (size > 62) {
		if (size & 0x1f) {
			size += 32;
		}
		size >>= 5;
		size -= 1;
		size |= 0x20;	//set BSIZE bit
	} else {
		if (size & 1) {
			size ++;
		}
		size >>= 1;
	}
	USB_SET_EP_RX_COUNT(ep, size << 10);
}
```

**Comment by kuldeepdhaka** [comment]
```
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

static uint16_t calc_current(uint32_t size)
{
	if (size > 62) {
		if (size & 0x1f) {
			size -= 32;
		}
		return (size << 5) | 0x8000;
	} else {
		if (size & 1) {
			size++;
		}
		return size << 10;
	}
}

static uint16_t calc_new(uint32_t size)
{
	if (size > 62) {
		size += 31; //round up to nearest mult. of 32
		size >>= 5;
		size -= 1;
		size |= 0x20;   //set BL_SIZE bit
	} else {
		if (size == 0) {        // illegal...
			size = 2;
		}
		size++;
		size >>= 1;     //round up and divide by 2
	}

	return size << 10;
}

#define BL_SIZE_SHIFT 15
#define NUM_BLOCK_SHIFT 10
#define NUM_BLOCK_MASK (0x1F << NUM_BLOCK_SHIFT)

static void test(uint16_t result, uint16_t size, uint16_t (*calc)(uint32_t))
{
	uint16_t actual_result = calc(size);
	if (result != actual_result) {
		printf("FAIL expected-result=%"PRIx16", "
				"actual-result=%"PRIx16", "
				"size=%"PRIu16"\n",
				result, actual_result, size);
	} else {
		printf("PASS result=%"PRIx16", "
				"size=%"PRIu16"\n", result, size);
	}
}

void test_func(const char *name, uint16_t (*calc)(uint32_t))
{
	unsigned i;

	printf("============= %s =========\n", name);

	/* for size=2..62 */
	for (i = 1; i < 31; i++) {
		test((0 << BL_SIZE_SHIFT) | (i << NUM_BLOCK_SHIFT), i * 2, calc);
	}

	/* for size=32, 64, 96 ... 992 */
	for (i = 0; i < 31; i++) {
		test((1 << BL_SIZE_SHIFT) | (i << NUM_BLOCK_SHIFT), (i + 1) * 32, calc);
	}
}

int main()
{
	test_func("calc_current", calc_current);
	test_func("calc_new", calc_new);
}
```

============= calc_current =========
FAIL expected-result=400, actual-result=800, size=2
FAIL expected-result=800, actual-result=1000, size=4
FAIL expected-result=c00, actual-result=1800, size=6
FAIL expected-result=1000, actual-result=2000, size=8
FAIL expected-result=1400, actual-result=2800, size=10
FAIL expected-result=1800, actual-result=3000, size=12
FAIL expected-result=1c00, actual-result=3800, size=14
FAIL expected-result=2000, actual-result=4000, size=16
FAIL expected-result=2400, actual-result=4800, size=18
FAIL expected-result=2800, actual-result=5000, size=20
FAIL expected-result=2c00, actual-result=5800, size=22
FAIL expected-result=3000, actual-result=6000, size=24
FAIL expected-result=3400, actual-result=6800, size=26
FAIL expected-result=3800, actual-result=7000, size=28
FAIL expected-result=3c00, actual-result=7800, size=30
FAIL expected-result=4000, actual-result=8000, size=32
FAIL expected-result=4400, actual-result=8800, size=34
FAIL expected-result=4800, actual-result=9000, size=36
FAIL expected-result=4c00, actual-result=9800, size=38
FAIL expected-result=5000, actual-result=a000, size=40
FAIL expected-result=5400, actual-result=a800, size=42
FAIL expected-result=5800, actual-result=b000, size=44
FAIL expected-result=5c00, actual-result=b800, size=46
FAIL expected-result=6000, actual-result=c000, size=48
FAIL expected-result=6400, actual-result=c800, size=50
FAIL expected-result=6800, actual-result=d000, size=52
FAIL expected-result=6c00, actual-result=d800, size=54
FAIL expected-result=7000, actual-result=e000, size=56
FAIL expected-result=7400, actual-result=e800, size=58
FAIL expected-result=7800, actual-result=f000, size=60
PASS result=8000, size=32
FAIL expected-result=8400, actual-result=8800, size=64
FAIL expected-result=8800, actual-result=8c00, size=96
FAIL expected-result=8c00, actual-result=9000, size=128
FAIL expected-result=9000, actual-result=9400, size=160
FAIL expected-result=9400, actual-result=9800, size=192
FAIL expected-result=9800, actual-result=9c00, size=224
FAIL expected-result=9c00, actual-result=a000, size=256
FAIL expected-result=a000, actual-result=a400, size=288
FAIL expected-result=a400, actual-result=a800, size=320
FAIL expected-result=a800, actual-result=ac00, size=352
FAIL expected-result=ac00, actual-result=b000, size=384
FAIL expected-result=b000, actual-result=b400, size=416
FAIL expected-result=b400, actual-result=b800, size=448
FAIL expected-result=b800, actual-result=bc00, size=480
FAIL expected-result=bc00, actual-result=c000, size=512
FAIL expected-result=c000, actual-result=c400, size=544
FAIL expected-result=c400, actual-result=c800, size=576
FAIL expected-result=c800, actual-result=cc00, size=608
FAIL expected-result=cc00, actual-result=d000, size=640
FAIL expected-result=d000, actual-result=d400, size=672
FAIL expected-result=d400, actual-result=d800, size=704
FAIL expected-result=d800, actual-result=dc00, size=736
FAIL expected-result=dc00, actual-result=e000, size=768
FAIL expected-result=e000, actual-result=e400, size=800
FAIL expected-result=e400, actual-result=e800, size=832
FAIL expected-result=e800, actual-result=ec00, size=864
FAIL expected-result=ec00, actual-result=f000, size=896
FAIL expected-result=f000, actual-result=f400, size=928
FAIL expected-result=f400, actual-result=f800, size=960
FAIL expected-result=f800, actual-result=fc00, size=992
============= calc_new =========
PASS result=400, size=2
PASS result=800, size=4
PASS result=c00, size=6
PASS result=1000, size=8
PASS result=1400, size=10
PASS result=1800, size=12
PASS result=1c00, size=14
PASS result=2000, size=16
PASS result=2400, size=18
PASS result=2800, size=20
PASS result=2c00, size=22
PASS result=3000, size=24
PASS result=3400, size=26
PASS result=3800, size=28
PASS result=3c00, size=30
PASS result=4000, size=32
PASS result=4400, size=34
PASS result=4800, size=36
PASS result=4c00, size=38
PASS result=5000, size=40
PASS result=5400, size=42
PASS result=5800, size=44
PASS result=5c00, size=46
PASS result=6000, size=48
PASS result=6400, size=50
PASS result=6800, size=52
PASS result=6c00, size=54
PASS result=7000, size=56
PASS result=7400, size=58
PASS result=7800, size=60
FAIL expected-result=8000, actual-result=4000, size=32
PASS result=8400, size=64
PASS result=8800, size=96
PASS result=8c00, size=128
PASS result=9000, size=160
PASS result=9400, size=192
PASS result=9800, size=224
PASS result=9c00, size=256
PASS result=a000, size=288
PASS result=a400, size=320
PASS result=a800, size=352
PASS result=ac00, size=384
PASS result=b000, size=416
PASS result=b400, size=448
PASS result=b800, size=480
PASS result=bc00, size=512
PASS result=c000, size=544
PASS result=c400, size=576
PASS result=c800, size=608
PASS result=cc00, size=640
PASS result=d000, size=672
PASS result=d400, size=704
PASS result=d800, size=736
PASS result=dc00, size=768
PASS result=e000, size=800
PASS result=e400, size=832
PASS result=e800, size=864
PASS result=ec00, size=896
PASS result=f000, size=928
PASS result=f400, size=960
PASS result=f800, size=992



so, this proves that this PR is useful and fix a actual problem.
@fenugrec good work!

**Comment by fenugrec** [comment]
Rebased the commit and updated PR name.

**Comment by karlp** [comment]
I'm wondering whether it wouldn't be best to change the API here to to return teh number of bytes actually allocated?

**Comment by fenugrec** [comment]
May I direct your attention to line 47 of the ancient scrolls of PR 880 !
https://github.com/libopencm3/libopencm3/pull/880/commits/4d8076ebab0145ad753497f2efce0b95cb00d724#diff-8ac26e98bbf7121474dfa16940d813f0R47

**Comment by karlp** [comment]
yeah, I found it myself later looking at different chunks of this.
