### ISSUE TITLE
USB: setup packet endianness

### ISSUE THREAD

**Issue by fenugrec** [libopencm3/libopencm3#478]
in usb_control.c::_usbd_control_setup(), the received packet is written directly (byte per byte) to a "struct usb_setup_data", which looks like this:
```
struct usb_setup_data {
	uint8_t bmRequestType;
	uint8_t bRequest;
	uint16_t wValue;
	uint16_t wIndex;
	uint16_t wLength;
}
```
USB is little-endian; as are most Cortex mcus. So this works in most cases, but if a big-endian uC is ever supported, _usbd_control_setup() will need to be changed.
A possible patch, after the usbd_ep_read_packet() call, could look like
```
#ifdef BIGEND /* use appropriate #ifdef here */
	#define FLIPENDIAN16(x)	(((uint8_t) ((x) >> 8)) | (((uint8_t) (x)) << 8))
	/* swap uint16 members on big-endian platforms */
	req->wIndex = FLIPENDIAN16(req->wIndex);
	req->wLength = FLIPENDIAN16(req->wLength);
	req->wValue = FLIPENDIAN16(req->wValue);
#endif
```

**Comment by karlp** [comment]
Valid, and yes, cortex-m is optional endianness for the implementor, but I'm not aware of any implementations that are big endian, and until someone finds one, I don't see any reason for this library to concern it self with endianness at all.
