### ISSUE TITLE
USB_REQ_TYPE_IN counterpart USB_REQ_TYPE_OUT not defined

### ISSUE THREAD

**Issue by kuldeepdhaka** [libopencm3/libopencm3#515]
USB_REQ_TYPE_IN is defined 0x80 but
USB_REQ_TYPE_OUT (0x00) is not
https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/usb/usbstd.h#L68

**Comment by karlp** [comment]
I guess?  https://github.com/libopencm3/libopencm3/blob/master/include/libopencm3/usb/usbstd.h#L76 is the bit, you can kinda look at the _IN as being a shifted field value and the _DIRECTION as the shift?

if you just do if (reqType & _DIRECTION) { // IN } else { // out }

if you want to do if (reqType & _DIRECTION == [_IN|_OUT]) {  //something } then yeah, I'm sure we can add a direction
