### ISSUE TITLE
F3 ADC definitions renamed

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3#548]
I'm planning on renaming a pile of definitions for the F3 ADC peripheral (F30x style) to use naming more in line with f0/l0/l4, that share the same peripheral.  It's not much, just 
```
- ADC_CFGR_XXX
+ ADC_CFGR1_XXX
```

This means we can use the same code for both of them.

**Comment by karlp** [comment]
After conversations, I'm going to attempt to add the ADC_CFGR defintions for f3 only, as aliases for ADC_CFGR1

**Comment by esden** [comment]
@karlp this patch looks good to me. Should we make the "old macros" generate compiler warnings that the CFGR style is legacy and might be removed in a future release?

**Comment by esden** [comment]
Ahh I see, this is part of a series, that is a draft pull request #555

**Comment by karlp** [comment]
this tree has landed
