### ISSUE TITLE
adc_v2: adc_start_conversion_regular() causes a freeze if ADC is timer-triggered

### ISSUE THREAD

**Issue by MightyPork** [libopencm3/libopencm3#557]
I'm working with stm32f3.

Timer is sending TRGO event to ADC, but it does not start converting until `ADSTART` is set.

I tried using `adc_start_conversion_regular()`, which seemed like the obvious right choice.

However, `adc_start_conversion_regular()` waits for `ADSTART` to be cleared after it sets it, which does not happen in all cases (see datasheet):

> It is cleared by hardware:
>   – in single conversion mode when software trigger is selected (EXTSEL=0x0): at the assertion of the End of Regular Conversion Sequence (EOS) flag.
>   – in all cases: after the execution of the ADSTP command, at the same time that ADSTP is cleared by hardware.
>     0: No ADC regular conversion is ongoing.
>     1: Write 1 to start regular conversions. Read 1 means that the ADC is operating and eventually converting a regular channel.

**Function with the bug**
https://github.com/libopencm3/libopencm3/blob/master/lib/stm32/f3/adc.c#L487

``` c
void adc_start_conversion_regular(uint32_t adc)
{
    /* Start conversion on regular channels. */
    ADC_CR(adc) |= ADC_CR_ADSTART;

    /* Wait until the ADC starts the conversion. */
    while (ADC_CR(adc) & ADC_CR_ADSTART);
}
```

The while loop should be removed.

If I use `ADC_CR(adc) |= ADC_CR_ADSTART;` manually, it works fine.

**Comment by karlp** [comment]
Totally correct. something that should be handled by further tests in https://github.com/karlp/libopencm3-tests/tree/master/tests/adc-power but I ran out of time there (for now)  needs some timer triggered stuff added to catch more differences like this.  This was some badly ported code in the original f3 commits (like a lot of that code unfortuntely :(
