### ISSUE TITLE
Common function names

### ISSUE THREAD

**Issue by drozel** [libopencm3/libopencm3#570]
I`m trying to use libopencm3 with contiki OS and see functions with the identical names in both libs, for example, timer_reset() in timer_common_all.c.
It would be effective to use function name prefix, like HAL_func(...) in STM HAL (sorry for this comparsion).

**Comment by karlp** [comment]
true of course.  You filed the same bug with contiki too right? ;)

There's some work going on to reduce the namespace pollution, but this isn't an area I believe anyone has any plans on addressing anytime soon.

**Comment by karlp** [comment]
No follow up, no intention of doing any explicit work here at present without further arguments.
