### ISSUE TITLE
STM32f0 is missing i2c code

### ISSUE THREAD

**Issue by plaes** [libopencm3/libopencm3#586]
Currently the stm32f0 is missing i2c code in the library.

Unfortunately it isn't as simple as just using the i2c_common include because the `I2C_CR1` layout is different (and quite probably something else too).

There's also a bug in libopencm3 docs which advertise i2c API: https://libopencm3.github.io/docs/latest/stm32f0/html/group__i2c__file.html

**Comment by karlp** [comment]
This was fixed initially back in ef91856a Sorry I missed closing it earlier.
