### ISSUE TITLE
Compiles fails on master with error rcc.c:55:3: error: unknown field 'ahb_frequency' specified in initializer

### ISSUE THREAD

**Issue by kungjohan** [libopencm3/libopencm3#625]
I get the following output when i try to compile libopencm3
latest commit is 770878e7b4ac12513e121e087261ca0972ba04e6

  CC      rcc.c
rcc.c:55:3: error: unknown field 'ahb_frequency' specified in initializer
   .ahb_frequency = 44000000,
   ^
rcc.c:55:3: warning: large integer implicitly truncated to unsigned type [-Woverflow]
rcc.c:55:3: warning: initialized field overwritten [-Woverride-init]
rcc.c:55:3: warning: (near initialization for 'rcc_hsi_8mhz[0].hpre') [-Woverride-init]
rcc.c:66:3: error: unknown field 'ahb_frequency' specified in initializer
   .ahb_frequency = 48000000,
   ^
rcc.c:66:3: warning: large integer implicitly truncated to unsigned type [-Woverflow]
rcc.c:66:3: warning: initialized field overwritten [-Woverride-init]
rcc.c:66:3: warning: (near initialization for 'rcc_hsi_8mhz[1].hpre') [-Woverride-init]
rcc.c:77:3: error: unknown field 'ahb_frequency' specified in initializer
   .ahb_frequency = 64000000,
   ^
rcc.c:77:3: warning: large integer implicitly truncated to unsigned type [-Woverflow]
rcc.c:77:3: warning: initialized field overwritten [-Woverride-init]
rcc.c:77:3: warning: (near initialization for 'rcc_hsi_8mhz[2].hpre') [-Woverride-init]
rcc.c: In function 'rcc_clock_setup_hsi':
rcc.c:430:28: error: 'const struct rcc_clock_scale' has no member named 'ahb_frequency'
  rcc_ahb_frequency  = clock->ahb_frequency;
                            ^
../../Makefile.include:44: recipe for target 'rcc.o' failed
make[1]: *** [rcc.o] Error 1
Makefile:61: recipe for target 'lib/stm32/f3' failed
make: *** [lib/stm32/f3] Error 2

**Comment by karlp** [comment]
I'm so sorry :(  I merged without further checks I never even considered that such a check hadn't even been compiled by it's author :( Fixed in 5738e95
