### ISSUE TITLE
STM32F0 rcc_set_ppre:  Documentation wrong

### ISSUE THREAD

**Issue by ha-ko** [libopencm3/libopencm3#636]
Hi,

In the documentation for rcc_set_ppre it says:
Note
    The APB1 clock frequency must not exceed 36MHz.

However in the data sheet 
RM0091
Reference manual
STM32F0x1/STM32F0x2/STM32F0x8
advanced ARM®-based 32-bit MCUs

on page 101 it says: 
" The AHB and the APB domains maximum frequency is 48 MHz."

**Comment by karlp** [comment]
checked f1, l0 and f0, restrictions listed in comments for other parts are correct.
