### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by davids5** [libopencm3/libopencm3#684]
I have noticed that PRs are not merge to master and left open. 

What is the status of this project? 
Who is/are the member(s) responsible for merging? 
What can we do to help?

Also note: I have the honor of of posting this issues that makes the Number of Issues == Number of Pull Requests.  :)

**Comment by karlp** [comment]
PRs are merged to master, but not all of them, and not all of them nearly as promptly as some people would like.  Some PRs are proposals, currently unmergable, previews, alternatives, or simply left for the sake of archiving old ideas.

The "status" of this project is kinda open of course.  For various targets, it's "complete" for others it's barely started.  Some people make a single drive by drop off of support for an uncommon target, but with no way of testing anything, it's hard to keep it, or even know whether to merge it.

There are 5-6 people with merge commit rights, myself being one of them, but virtually all of them are not active presently.  For a lot of early developers, it's simply "finished" for them.  For others, the motivation for this project itself is simply not there anymore, now that ST and ARM released more permissively licensed CMSIS header files.  (The original CMSIS header files released were incompatible with (L)GPL projects entirely)

@esden has ownership of the repository, and is the only one who can nominate more people with merge rights.

What you can do to help:
* Not get upset that a merge takes more than 3-4 days.
* Provide commits that you've already reviewed, that have consistent style (```make stylecheck```), that have consistent commit comment formatting, that don't pull one target in a different direction, that fix a complete issue, not just patching a certain path for a certain target.
* if at all possible, include a multi platform test case, ideally automated.  You can see some examples in the tests/ directory, and I've got more planned.

In the past, merges were faster and looser, with people promising to refactor and cleanup "later" which simply never happened.  Most contributors are generally only interested in their own target, not other targets using the same code.  This over time led to far far more maintennance overhead and inconsistency.  This leads _me_ to be quite conservative in what I merge.  Personally I've also had substantially less time than expected this spring and summer, which has not helped.
