### ISSUE TITLE
stm32f42x/f43x voltage ranges not supported

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3#685]
The existing f4 rcc clock setup helper treats "power save" as a boolean, instead of a field to simply pass to the power function.

Further, and more importantly, it's missing a call to `rcc_periph_clock_enable(RCC_PWR);` before setup.  Noticed while working on a bug in this area with L1 and checking other families, but don't have an f4 board handy to test out.

**Comment by karlp** [comment]
(And of course, the pwr_set_vos_scale() call for f4 is also non-functional for these families)

**Comment by ChuckM** [comment]
Yes this covers it. Thanks

**Comment by karlp** [comment]
this was fixed via cc8c8a2f aiui
