### ISSUE TITLE
efm32lg: dma.c: no previous prototype for 'dma_calc_end_from_start'

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3#686]
@kuldeepdhaka inline uint32_t dma_calc_end_from_start() is the only inline function. does it need to be inline? and either way, is it meant to be a public function, in which case it needs a header def to kill this warning, or it needs to be made static with a prototype for use in dma.c only to also kill the warning.

**Comment by kuldeepdhaka** [comment]
@karlp it should probebly be static.
afair, it is intended for dma.c only.

**Comment by karlp** [comment]
good enough for me will fix it up

**Comment by karlp** [comment]
merged and fixed
