### ISSUE TITLE
Duplicate functions eth_smi_read/write for stm32f1

### ISSUE THREAD

**Issue by 6006l1k** [libopencm3/libopencm3#694]
The functions `eth_smi_read` and `eth_smi_write` is defined twice:

https://github.com/libopencm3/libopencm3/blob/6c034c89815e8fb33471d35ed0afe449e34618b5/lib/ethernet/mac_stm32fxx7.c#L305

https://github.com/libopencm3/libopencm3/blob/6c034c89815e8fb33471d35ed0afe449e34618b5/lib/stm32/f1/ethernet.c#L22

**Comment by karlp** [comment]
oh, doh, sorry,thanks for closing this, missed the issue it self.  Thanks for reporting this!
