### ISSUE TITLE
genlinktests failing

### ISSUE THREAD

**Issue by Jak-o-Shadows** [libopencm3/libopencm3#703]
On my CENTOS 7 system with awk 4.0.2, the awk script fails. Note that it also fails the genlinktests.

Occurs after commit 60ca09c61e28a86f7bfc2133503cc603f415d3a8 ie. commit c025dc0327c44dbaaca90e9f179ef6fe44aa233b works.

Note that simply reverting this file is not a fix - if you do so, -DSTM32F4 (etc) is not included anywhere, and you get a compiler error instead.

**Comment by karlp** [comment]
no longer relevant, it no longer exists.
