### ISSUE TITLE
RFC: drop timer_reset(timer) function

### ISSUE THREAD

**Issue by karlp** [libopencm3/libopencm3#709]
This method is simply a wrapper for rcc_periph_reset_pulse() but done badly, and incompletely.  

options/opinions?

a) Drop it outright, break existing apps, but no claim of abi compat anyway without any tagged release
b) __attribute__ deprecated or warning, leave existing partial code until..... when? (forever?)
c) as b) but at least drop the current partial code

**Comment by karlp** [comment]
Can also go and replace all _example_ code right now, then wait a few months and drop it completely?

**Comment by ChuckM** [comment]
Of the three I like option c. Breaking code is 'ok' in my mind at this point because in many ways the code is already broken and the developer doesn't know it.

**Comment by karlp** [comment]
Propose the following steps for "now"

1. update all examples
2. add attribute deprecated and expand docs to indicate incomplete and what to use instead

"Later"

1. drop it

**Comment by karlp** [comment]
I've got this in my staging now to drop it outright now that we've had the better alternative for over a year
