### ISSUE TITLE
RCC_CSR_RTCEN for STM32L0 is wrong

### ISSUE THREAD

**Issue by samedcildir** [libopencm3/libopencm3#720]
libopencm3/include/libopencm3/stm32/l0/rcc.h line 456-457
```c
#define RCC_CSR_RTCRST (1 << 19)
#define RCC_CSR_RTCEN	 (1 << 19)
```

According to STM32L0x3 reference manual (RM0367) 7.3.21, `RCC_CSR_RTCEN` should be `(1 << 18)`

**Comment by karlp** [comment]
indeed, thanks for reporting this.  fixed in 7c3d39f
