### ISSUE TITLE
Documentation for SPI on STM32F1 is not showing up

### ISSUE THREAD

**Issue by NikolayBobovnikov** [libopencm3/libopencm3#739]
[Documentation](http://libopencm3.github.io/docs/latest/stm32f1/html/group__spi__file.html) on SPI module for STM32 F1 chip is not showing up when pressing "More..."

Since including "spi.h" in the project for F1 chip leads to including "spi_common_l1f124.h", I suppose [details page for F1](http://libopencm3.github.io/docs/latest/stm32f1/html/group__spi__file.html#details) should redirect to [page for L1](http://libopencm3.github.io/docs/latest/stm32l1/html/group__spi__file.html)?

Regards,
Nikolay

**Comment by esden** [comment]
We are currently transferring the domains around. So the links you are referring to might not be working correctly for the next few days. I will try to look into it as soon as the dust settles a bit. :)

**Comment by NikolayBobovnikov** [comment]
Ah, ok. At least this is known :)

**Comment by karlp** [comment]
still broken, looks to just be more doxygen bustage

**Comment by karlp** [comment]
This should all be fixed now, I've overhauled the doxygen generation to be based on the sources compiled.
