### ISSUE TITLE
[Q] Replace register-level API with CMSIS

### ISSUE THREAD

**Issue by ildar** [libopencm3/libopencm3#751]
I know that CMSIS once was proprietary. But it's no more so (it is BSD-lic).
I think it's not great that the 2 APIs: both libopencm3 and CMSIS making the same things. I guess that CMSIS has no disadvantages compared to libopencm3 (at register level). And it is quite stable and widely supported.
Is it about the time to drop register-level (of opencm3) in favor of the CMSIS ?
Opinions?

**Comment by karlp** [comment]
simply too much work.  You're effectively looking at an entirely new project at that point.  But yes, some of the original motivation of this project is substantially less clear now that the CMSIS headers are available under a more acceptable license.  Also, while the register addresses and offsets might be replaceable, all the field definitions and APIs would end up being incompatible, you'd really be at a new, but different project.
