### ISSUE TITLE
Check stm32f7 flash differences

### ISSUE THREAD

**Issue by matthewlai** [libopencm3/libopencm3#765]
stm32f7/flash.h now includes flash_common_f24.h, but F7's flash is not actually backward compatible. For example, there's no longer separate d-cache and i-cache, but a unified cache. This is especially confusing because Cortex-M7 does have CPU d-cache and i-cache, but they are on the AXIM bus, not on the ITCM bus.

I will also merge other differences, and probably refactor flash_common_* into v1/v2/v3.

AN4660 lists peripheral differences between F4 and F7.

**Comment by karlp** [comment]
I believe all of this was covered via the original merge of @matthewlai 's code, as well as the later cleanups and refactorins in 9dd901ba..659d52b9
