### ISSUE TITLE
Strange behavior of usbd_ep_write_packet() when len equals to EP max packet size

### ISSUE THREAD

**Issue by katyo** [libopencm3/libopencm3#791]
I found that packet doesn't sent to host from device when the length of data is equals to max size of packet for endpoint.
I suggested that this happens only with my app, so I tried USB CDC example and found the same strange behavior.
I use wireshark to capture and analyze USB packets.
I started GDB and set breakpoint to cdcacm_data_rx_cb(), next I seen that the callback is called as expected and all 64 bytes read from OUT EP, but after writing to IN EP I don't capture expected bulk packet on the bus.
When I reduce packet size to 63 bytes (or less), all works as expected and I captured both bulk packets.

UPD:
I changed the max packet size to 32 bytes. Now I can successfully send and receive 31 bytes only.

**Comment by devanlai** [comment]
You may need to send a zero-length packet after sending a packet of the maximum packet size before the host USB stack will consider the USB transfer complete and pass the data onto the application:
http://stackoverflow.com/questions/41855995/when-should-a-usb-device-send-a-zlp-on-a-bulk-pipe

**Comment by katyo** [comment]
As I understand I need use cdcacm_data_tx callback to send ZLP.

**Comment by karlp** [comment]
I'm not really sure what you're issue is here.  I'd advise looking at all the tests inthe gadget-zero code that exercise all sorts of different read/write lengths.
