### ISSUE TITLE
USB interrupt problem in STM32

### ISSUE THREAD

**Issue by Kathir007** [libopencm3/libopencm3#814]
Hai,
         I faced the problm in stm32l151cb called usb interrupt during the Run in battery mode. When the Stm32l151cb running in battery mode , suddenly insert the usb cable , STM32l151cb can changed to USB mode(5v) immediately but VCP is not working in this time, pls help me to solve this issue

**Comment by karlp** [comment]
Please, we need more information if we're to diagnose this further.  There's no support at present for any of the usb power management features in libopencm3.  I realise this is quite old, and I'm sorry we didn't answer you earlier.  Please re-open this ifyou're still having issues and have new information.
