### ISSUE TITLE
Missing STM32L4 support?

### ISSUE THREAD

**Issue by davidgfnet** [libopencm3/libopencm3#823]
Hey!
Just noticed that there's no support for -DSTM32L4 in: include/libopencmsis/dispatch/irqhandlers.h, include/libopencm3/stm32/exti.h. Also missing files like include/libopencm3/stm32/l4/exti.h and many others.

Is this intended? Am I missing some magical define? I'm only using -DSTM32L4

Thanks!
David

**Comment by karlp** [comment]
libopencmsis is a stub for some efm support, you can just use normal cmsis headers now that they've been relicensed.  exti hasn't been tested/verified on l4, so it's not been enabled.  It's probably the same exti peripheral, so you can try adding the defines and adding it to the build if you like.
