### ISSUE TITLE
FLASH_ACR_LATENCY_4WS missing for STM32L4

### ISSUE THREAD

**Issue by davidgfnet** [libopencm3/libopencm3#832]
File include/libopencm3/stm32/l4/flash.h is missing a definiton for FLASH_ACR_LATENCY_4WS

Some parts need this to reach 80MHz.

**Comment by davidgfnet** [comment]
Oh now that I look closely, isn't it just wrong? The latency bits are LSB, yet FLASH_ACR_LATENCY_SHIFT is non zero. The mask is also wrong, should be Fh.
I'm not sending PR for these bugs I find cause I'd like someone to confirm that I'm not talking BS here :D

**Comment by karlp** [comment]
thanks for the report! not sure why this was wrong, even the original ref mans I have stillhad this as a three bit field.
