### ISSUE TITLE
STM32F303 timer "break" support

### ISSUE THREAD

**Issue by Gussy** [libopencm3/libopencm3#839]
The function [`timer_enable_break_main_output`](https://github.com/libopencm3/libopencm3/blob/af7b2190a97ddadd9e227cc6b0a4cf18d49cba12/lib/stm32/common/timer_common_all.c#L1598) is no-op for any timers that aren't "advanced".

TIM15 on the STM32F303x(D/E) isn't "advanced" however it does have the "break" feature, which needs to be enabled for the output to work, even if the break feature is not used.

The workaround for anyone else who runs into this is to just enable it directly in the register:
`TIM_BDTR(TIM15) |= TIM_BDTR_MOE;`

**Comment by karlp** [comment]
this has been fixed via merging the referenced PR above
