### ISSUE TITLE
STM32F7 USART Register is different to M4

### ISSUE THREAD

**Issue by yinjiajie** [libopencm3/libopencm3#852]
The F7 usart register is different to M4, it is necessary to update  F7 USART register?

**Comment by karlp** [comment]
The F7 has the same usart peripheral as the f3, f0, l0, l4, the "v2" peripheral.  You probably only need to implement a few pieces such as in https://github.com/libopencm3/libopencm3/commit/368a33773f2c7776f72dcf89c56ecc2b2ef4fe79 and https://github.com/libopencm3/libopencm3/commit/f67966046a5df2c29301b77d99c82b3a4805b8e8

The f7 memorymap is already in place.  This is one of many parts of the f7 that is known to be incomplete, so I'm closing this ticket.
