### ISSUE TITLE
stm32/l4/usart.h missing

### ISSUE THREAD

**Issue by rjordans** [libopencm3/libopencm3#853]
After updating I get the following error on compiling the library:

```
 In file included from ../common/usart_common_all.c:33:0:
 ../../../include/libopencm3/stm32/usart.h:38:46: fatal error: libopencm3/stm32/l4/usart.h: No such file or directory
  #       include <libopencm3/stm32/l4/usart.h> 
```

It seems that support for USART on l4 has been committed but misses the target specific header file

**Comment by rjordans** [comment]
See also f679660

**Comment by karlp** [comment]
Yeah I know, noticed about 5 minutes after pushing :(  it's sitting uncommitted on my pc at home, will push it when I get back :(
