### ISSUE TITLE
rcc_clock_setup_in_hse_8mhz_out_72mhz not working with 8mhz quarz

### ISSUE THREAD

**Issue by Tarcontar** [libopencm3/libopencm3#910]
Hi, 
I am working with an stm32 f100 on an discovery board,
i got rcc_clock_setup_in_hse_12mhz_out_72mhz
and rcc_clock_setup_in_hse_16mhz_out_72mhz
working with no problems, when i use the 16 variant the led blinks twice as slow as it should,
since there is only a 8mhz quarz installed.
But when I try to use the 8mhz variant it doesnt blink at all.
I checked the source code and found only two small differences in these two functions.
Is there anything I am missing?

Greetings 
Tarcontar

**Comment by karlp** [comment]
you're meant to use the version that matches the crystal you have installed.  All bets are off if you're not following that basic guideline.  You could easily be exceeding pll maxes/mins for instance.

In your particular case though, you're simply attempting to overclock your f100 by ~300%.  It's only rated to 24Mhz  http://www.st.com/en/microcontrollers/stm32f100-value-line.html?querycriteria=productId=LN775

Anything beyond that is luck and not something we can help with.

**Comment by Tarcontar** [comment]
kk thanks
