### ISSUE TITLE
Make it possible to build firmwares using Linaro GCC 7.2.1 toolchain

### ISSUE THREAD

**Issue by joe-skb7** [libopencm3/libopencm3#912]
Hi,

Linaro toolchain is quite popular for ARM baremetal software right now:

https://releases.linaro.org/components/toolchain/binaries/7.2-2017.11/arm-eabi/

So I decided to give it a try for my firmware, which uses libopencm3 (previously I was using the one from `gcc-arm-none-eabi` Debian testing package, which is GCC 6.3.1). And although libopencm3 was built just fine with new toolchain, I started to see next linking errors when building my firmware:

    .../arm-eabi/bin/ld: my-firmware.elf section `.text' will not fit in region `rom'
    .../arm-eabi/bin/ld: region `rom' overflowed by 56136 bytes

Indeed, the `.text`section grew drastically. With Debian toolchain I had next stats:

    .text           = 0x00b620
    my-firmware.bin = 49 KiB
    my-firmware.elf = 708 KiB

With Linaro toolchain it's:

    .text           = 0x02cf30
    my-firmware.bin = 183 KiB
    my-firmware.elf = 1.3 MiB

After doing a bit of investigation like this:

    $ ${CROSS_COMPILE}nm --print-size --size-sort --radix=d my-firmware.elf

I've found out that:
 * the difference is mainly because of some new symbols were added (like `get_arg()` function) and also `_vfprintf_r()` size was increased
 * apparently those are newlib functions
 * After comparing `${CROSS_COMPILE}gcc -v` output, I figured that Debian toolchain is built using `--without-newlib` flag, but Linaro toolchain is built using `--with-newlib` flag. Can it be the issue?.. Also, this is **weird**, I thought we are using some newlib functionality for `printf()` (which I'm using in my firmware successfully)
 * `--gc-sections` doesn't help in this case, obviously
 * removing `-lc -lgcc -lnosys` linking options didn't help, too (I wanted to disable linking against newlib this way)
 * when I disable all `printf()` functions in my code, the size of firmware becomes fine (20 KiB for `my-firmware.bin`); so the size problem is mainly in `printf()` related functions, like maybe `_vfprintf_r()`

Regarding this I have two questions:
 1. Am I correct that the size gain of my FW is due to toolchain's `--with-newlib` option?
 2. If so, is there any way to disable newlib when building my firmware (so that the behavior would be the same as in Debian toolchain)?

Further I'm going to:
 1. Look how this issue is solved in U-Boot
 2. Ask Linaro toolchain engineers the same question

If someone knows why the FW size is increased when using Linaro toolchain, and how to fix it, please advice.

Thank you!

**Comment by karlp** [comment]
the way to fix it is to not use it.  From their own website, they claim to be targetting cortex-A.  _many_ assumptions and decisions in that toolchain are simply going to be inappropriate.  the newlib points are likely a red herring.  The regular arm-none toolchains from arm supply multiple newlib options, of various sizes, so they probably show up as "no newlib" in gcc-s output, as they're not fixed.  uboot is irrelevant again, as that's also not targetting cortex-m.
