### ISSUE TITLE
No support for SPI in STM32L0 port

### ISSUE THREAD

**Issue by MarSik** [libopencm3/libopencm3#913]
There are no includes with SPI functions for STM32L0.

**Comment by karlp** [comment]
yes. there are.  Please elaborate in substanttially more detail if you want to file a bug like this.

**Comment by MarSik** [comment]
Ah, the support was just commited as part of #740 and #742. Sorry for the noise.

**Comment by MarSik** [comment]
Btw, github says the patch was merged yesterday so I was not too late.
