### ISSUE TITLE
No support for DMA in STM32L0

### ISSUE THREAD

**Issue by MarSik** [libopencm3/libopencm3#914]
There are no includes with DMA functions for STM32L0.

**Comment by karlp** [comment]
there's lots of peripherals on lots of hardware that isn't supported, we cannot have a ticket for every peripheral on every single target, that wouldn't even be helpful to track anything.  DMA on l0 probably needs very little testing and adding in the common dma code.  Feel free to open a PR for that, but I'm not going to keep broad tickets like this open.

**Comment by MarSik** [comment]
How do you track missing peripherals then? Especially when the other platforms have the support ready? DMA is pretty core component for low power designs.. which is what L0 is about.

**Comment by karlp** [comment]
I don't.  You can edit and maintain pages on the wiki if you like, but it's an endless task, and never descriptive enough for people.
