### ISSUE TITLE
i2c_common_v2: ADDRIE bitmask is named I2C_CR1_DDRIE

### ISSUE THREAD

**Issue by tuankiet65** [libopencm3/libopencm3#925]
The bitmask should be named I2C_CR1_ADDRIE but is instead named I2C_CR1_DDRIE (spelling error?). I'm afraid to open a pull request though because this could be a breaking change so I'm looking for opinions regarding this issue.

https://github.com/libopencm3/libopencm3/blob/ed90df85f089d260fc598cb200b5d36678045ec0/include/libopencm3/stm32/common/i2c_common_v2.h#L157

**Comment by karlp** [comment]
Fixed in 2352d5d1 thanks!
