### ISSUE TITLE
Future Prospects of this Library

### ISSUE THREAD

**Issue by gracefulshark** [libopencm3/libopencm3#936]
We want to start a new open source hardware project, and libopencm3 may be very useful.

Judging from the number of commits this year and the general activity of this repository we have doubts concerning the future of this library. To put it simply, is it dead?

**Comment by karlp** [comment]
not dead, but slow and conservative.  we have very few regular committers actively working on things, and a lot of one off contributions, which then need cleanup and/or testing before they get merged.  It's certainly not going away in any form.
