### ISSUE TITLE
STM32F49I-DISCO : lcd-dma example not work with the last libopencm3 version

### ISSUE THREAD

**Issue by GaoTamanrasset** [libopencm3/libopencm3#937]
lcd-dma example (https://github.com/libopencm3/libopencm3-examples/tree/master/examples/stm32/f4/stm32f429i-discovery/lcd-dma) on stm32f429i discovery board, not work with the last libopencm3 version.

**Comment by karlp** [comment]
does it work with the version of the library that's int he examples repo?

**Comment by GaoTamanrasset** [comment]
Ha sorry, I thought version in the example repository was the lastest.
It does not work with libopencm3 version of the example repository.

**Comment by karlp** [comment]
ok, can you file this on that repository then please.  I'm afraid I don't have that board to do any testing with myself

**Comment by GaoTamanrasset** [comment]
No problem. Sorry for the noise.
