### ISSUE TITLE
Support for MSP432.

### ISSUE THREAD

**Issue by Misaka0x2730** [libopencm3/libopencm3#940]
Hello!
I want to try to improve the support of MSP432. The essence of this issue - should I continue developing as lm4f or do I need to create a separate folder for msp432?
Many thanks!

**Comment by Misaka0x2730** [comment]
Because of the question, whether MSP432 is a continuation of LM4F, my head has become very ill today :( If I understand everything correctly on the [site](http://www.ti.com/microcontrollers/simplelink-mcus/wired-mcus/overview/overview.html), TI consider MSP432 as part of the SimpleLink series.

**Comment by ChuckM** [comment]
I reviewed the web site, the MSP432 is a different family as far as TI is concerned so it should get its own target I believe.

**Comment by Misaka0x2730** [comment]
@karlp @ChuckM I carefully studied the technical reference manual and came to the conclusion that MSP432 needs its own target.
Example: GPIO Drive Strength. For LM4F - setting a bit in the GPIO_DRxR register clears the corresponding bit. Available 2-ma, 4-ma and 8-ma pad drive, slew rate control for 8-ma. 
For MSP432 - by default the same way. But when the EDE bit in GPIOPP is set, and the EDMn bit field is non-zero in the GPIOPC  - bit combinations possible. Available 2-ma, 4-ma, 6-ma, 8-ma, 10-ma and 12-ma pad drive, slew rate control for 8-ma, 10-ma and 12-ma. 
For more information - see [this](http://www.ti.com/lit/ug/slau723/slau723.pdf), sheet 1199.
