### ISSUE TITLE
STM32L0 - LPUART1 baud rate is not computed properly

### ISSUE THREAD

**Issue by MarSik** [libopencm3/libopencm3#951]
Low power usart configured as below does not work properly (it is too fast):

```
usart_set_baudrate(LPUART1, 9600);
```

The common usart code uses a baud rate formula that is valid for standard USART2, but LPUART1 uses a different one to compute the baud rate prescaler.

- USART2: USART_BRR(usart) = ((2 * clock) + baud) / (2 * baud) [1]
- LPUART1: Tx/Rx baud = 256 × Fclk / LPUARTDIV

See https://www.st.com/content/ccc/resource/technical/document/reference_manual/21/bd/0f/bd/1c/88/40/f0/DM00108282.pdf/files/DM00108282.pdf/jcr:content/translations/en.DM00108282.pdf page 730 section 25.4.4

[1] https://github.com/libopencm3/libopencm3/blob/master/lib/stm32/common/usart_common_all.c#L73

**Comment by karlp** [comment]
Handled via https://github.com/libopencm3/libopencm3/pull/888 and staged locally, will appear in master "soon"
