### ISSUE TITLE
stm32l011 linker script generator support

### ISSUE THREAD

**Issue by xor-gate** [libopencm3/libopencm3#954]
Hi all,

I'm using a STM32L011 Nucleo-32 devkit with a STM32L011K4T6 (32pins) but it seems to not be supported in the ld/devices.data. I have added it myself and it works fine, as it seems there is no matching device when i specify `DEVICE = stm32l011` from the project Makefile.

This line I have added: `stm32l011* stm32l0 ROM=16K RAM=2K`. I'm not sure if I specify it incorrect or it is just plain not supported.

Kind regards,
Jerry Jacobs

**Comment by karlp** [comment]
You're meant to do DEVICE=STM32L011K4T6 (any case), not just "stm32l011" 

Without the full name, you wouldn't be able to distinguish from the stm32l011k3t6, with only 8k flash.

**Comment by xor-gate** [comment]
That explains everything. Sorry for the noise.

**Comment by karlp** [comment]
No problem, feel very welcome to report issues.
