### ISSUE TITLE
CortexM0: NVIC priority registers support only word addressing

### ISSUE THREAD

**Issue by mattande** [libopencm3/libopencm3#957]
nvic_set_priority() handles all IPR register accesses using byte addressing, however on Cortex M0 all NVIC registers must only be accessed using word addressing.

See Cortex M0 TRM 5.1. About the NVIC:
All NVIC registers are only accessible using word transfers. Any attempt to read or write a halfword or byte individually is Unpredictable.

**Comment by karlp** [comment]
so, what does "unpredictable" actually do in practise?  (just curious, as you must have run into this)

**Comment by karlp** [comment]
oh right, I merged thsi one, and only commented on the other one, instead of here.  thanks for cleaning up behind me!
