### ISSUE TITLE
Build shared instead of static?

### ISSUE THREAD

**Issue by jiapei100** [libopencm3/libopencm3#966]
How to configure Makefile to build **shared libraries (*.so)** instead of **static libraries (*.a)**?

Cheers
Pei

**Comment by ChuckM** [comment]
There is no shared library mechanism for the Cortex-M architecture.

**Comment by karlp** [comment]
and if you build one for your system, it's out of scope of this project.  NuttX and I think even chibios hve some attempts at loading code at runtime.
