### ISSUE TITLE
Assembly support

### ISSUE THREAD

**Issue by alexkazik** [libopencm3/libopencm3#980]
Great project!
But I'd like to use it with assembler files. Maybe that can be added.

I adapted it to have basic support. 
The project compiles and runs on my board.
It's probably far away from being good though.

The diff is against libopencm3-template (including a change in this library).
[with-assemler.diff.txt](https://github.com/libopencm3/libopencm3/files/2458157/with-assemler.diff.txt)

**Comment by karlp** [comment]
Please make a regular PR if you want changes merged.  

If you want a change in the libopencm3-template, please make the PR there.
