### ISSUE TITLE
LGPL linking problem

### ISSUE THREAD

**Issue by ezaquarii** [libopencm3/libopencm3#987]
Is there any update on adding a linking clause to the licence?

Currently the page collects "feelings", which does not tell us much.

The reality is that if there are ***any*** doubts, there no ***no*** doubts, ie. the library will not be used in any serious project out of fear of being approached by competition or genuine trolls.

If your general feeling is that linking is allowed anyway, additional reassurance should not be a problem.

I must point out that LGPL licence mandates that the user must be provided with all necessary components allowing her to re-link changed, LGPL'd code. In case of embedded software, this is simply technically infeasible task, or at least very challenging - discouraging from using libopencm3.

I believe that the project would benefit greatly if legal situation could be rectified. Assurances by anonymous legal interpretations are enough for hobbyists, but will be ignored by anybody realistically being at legal risk.

Until this is rectified, Atollic/CubeMX/etc is _sadly_ pretty much the only viable option for serious users.

**Comment by karlp** [comment]
The only way it could happen at this stage would be a hard fork and dropping code. So for all practical concerns, it's not going to happen.  People are very aware of what the lgpl implies, but you may also be rather overestimating the difficulty.  Providing .o's and a makefile is perfectly adequate.  Remember further, you only have to do this to people you distribute too.
